import { Calendar } from "../../polyfills/Utils";
import { Parsha, JewishCalendar } from "../JewishCalendar";

/**
 * This class's main goal is to return the Weekly Haftorah reading said after the Weekly Parasha
 * reading. Which readings to say were taken from the Chumash "L'maan Shemo B'Ahavah" according to
 * the Sepharadic Minhag.
 * @see WeeklyParashaReadings
 */

type Unpacked<T> = T extends (infer U)[] ? U : T;

const entries = [
	"ADES: 24793" as const,
	"GABRIEL A SHREM 1964 SUHV" as const, // AKA ARTSCROLL
	"TABBUSH Ms NLI 8*7622, Aleppo" as const,
	"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905" as const,
	"TEBELE Pre1888" as const,
	"ELIE SHAUL COHEN FROM AINTAB, ~1880" as const,
	"YAAQOB ABADI-PARSIYA" as const,
	"YISHAQ YEQAR ARGENTINA" as const,
	"Dibre Shelomo S KASSIN Pre1915" as const,
	"Knis Betesh Geniza List, Aleppo" as const,
	"ABRAHAM DWECK Pre1920" as const,
	"IDELSOHN Pre1923" as const,
	"S SAGIR Laniado" as const,
	"M H Elias, SHIR HADASH, Jerusalem, 1930" as const,
	"ASHEAR list" as const,
	"ASHEAR NOTES 1936-1940" as const,
	"ABRAHAM E SHREM ~1945" as const,
	"Argentina 1947 & Ezra Mishanieh" as const,
	"Shire Zimra H S ABOUD Jerusalem, 1950" as const,
	"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO" as const,
	"YOSEF YEHEZKEL Jerusalem 1975" as const,
	"Ish Massliah \"Abia Renanot\" Tunisians" as const,
	"Shaare Zimra YANANI Buenos Aires, 01" as const,
	"BOZO, Ades, Shir Ushbaha 2005" as const,
	"Yishaq Yeranen Halabi" as const,
	"MOSHE AMASH (Shami)" as const,
	"EZRA MASLATON TARAB (Shami)" as const,
	"ABRAHAM SHAMRICHA (Shami)" as const,
	"Victor Afya, Istanbul List" as const,
	"Izak Alaluf, Izmir List" as const,
	"Hallel VeZimrah, Salonika, 1928" as const,
	"Hallel VeZimrah, Greece List, 1926" as const,
	"Ish Massliah \"Abia Renanot\" Tunisians" as const,
	"SASSOON #647 Aleppo, 1850" as const,
	"Eliahou Yaaqob DWECK-KESAR" as const
]

export default class WeeklyMakamReading {
	hierarchy: (Unpacked<typeof entries> | "MAJORITY")[];

	constructor(hierarchy=entries) {
		this.hierarchy = hierarchy;
	}

	getTodayMakam(jCal: JewishCalendar) {
		const data = WeeklyMakamReading.getMakamData(jCal);
		for (const entry of this.hierarchy) {
			if (entry == "MAJORITY")
				return findDuplicate(Object.values(data));

			if (entry in data) {
				return data[entry];
			}
		}
	}
	/**
	 * This method returns a string that contains the weekly Makam. The {@link JewishCalendar}
	 * object passed into this method should be preset with the correct date.
	 * @param jCal the JewishCalendar object set to Saturday
	 * @return All the data fields
	 */
	public static getMakamData(jCal: JewishCalendar): Partial<Record<Unpacked<typeof entries>, string>> {
		if (jCal.isYomTov()) {
			switch (jCal.getYomTovIndex()) {
				case JewishCalendar.ROSH_HASHANA:
					if (jCal.getJewishDayOfMonth() == 1)
						return {
							"Eliahou Yaaqob DWECK-KESAR": "Hoseni",
							"YISHAQ YEQAR ARGENTINA": "Hijaz",
							"IDELSOHN Pre1923": "Saba",
						}
					else 
						return {
							"Eliahou Yaaqob DWECK-KESAR": "Hoseni",
							"YISHAQ YEQAR ARGENTINA": "Hijaz",
							"IDELSOHN Pre1923": "Bayat"
						}
					break;
				case JewishCalendar.YOM_KIPPUR:
					return {
						"Eliahou Yaaqob DWECK-KESAR": "Hijaz Hoseni",
						"YISHAQ YEQAR ARGENTINA": "Hijaz",
						"IDELSOHN Pre1923": "Hijaz"
					};
					break;
				case JewishCalendar.SUCCOS:
					if (jCal.getJewishDayOfMonth() == 15)
						return {
							"SASSOON #647 Aleppo, 1850": "Sigah",
							"Eliahou Yaaqob DWECK-KESAR": "Sigah",
							"YAAQOB ABADI-PARSIYA": "Sigah",
							"YISHAQ YEQAR ARGENTINA": "Sigah",
							"ABRAHAM DWECK Pre1920": "Sigah",
							"IDELSOHN Pre1923": "Sigah",
							"S SAGIR Laniado": "Sigah",
							"ASHEAR list": "Sigah",
							"ASHEAR NOTES 1936-1940": "Sigah",
							"ABRAHAM E SHREM ~1945": "Sigah",
							"Argentina 1947 & Ezra Mishanieh": "Sigah",
							"Shire Zimra H S ABOUD Jerusalem, 1950": "Sigah",
							"GABRIEL A SHREM 1964 SUHV": "Sigah",
							"YOSEF YEHEZKEL Jerusalem 1975": "Ajam",
							"Ish Massliah \"Abia Renanot\" Tunisians": "Sigah",
							"Shaare Zimra YANANI Buenos Aires, 01": "Sigah",
							"BOZO, Ades, Shir Ushbaha 2005": "Sigah",
							"MOSHE AMASH (Shami)": "Rast",
							"EZRA MASLATON TARAB (Shami)": "Rast",
							"ABRAHAM SHAMRICHA (Shami)": "Rast",
							"Hallel VeZimrah, Greece List, 1926": "Sigah"
						}
					else
						return {
							"SASSOON #647 Aleppo, 1850": "Sasgar",
							"Eliahou Yaaqob DWECK-KESAR": "Ajam",
							"YAAQOB ABADI-PARSIYA": "Sasgar",
							"YISHAQ YEQAR ARGENTINA": "Ajam",
							"ABRAHAM DWECK Pre1920": "Sasgar",
							"S SAGIR Laniado": "Ajam",
							"ASHEAR list": "Ajam",
							"ASHEAR NOTES 1936-1940": "Ajam",
							"ABRAHAM E SHREM ~1945": "Ajam",
							"Argentina 1947 & Ezra Mishanieh": "Ajam",
							"Shire Zimra H S ABOUD Jerusalem, 1950": "Ajam",
							"GABRIEL A SHREM 1964 SUHV": "Ajam",
							"Ish Massliah \"Abia Renanot\" Tunisians": "Ajam",
							"Shaare Zimra YANANI Buenos Aires, 01": "Ajam",
							"BOZO, Ades, Shir Ushbaha 2005": "Ajam",
							"MOSHE AMASH (Shami)": "Sigah",
							"EZRA MASLATON TARAB (Shami)": "Sigah",
							"ABRAHAM SHAMRICHA (Shami)": "Bayat",
							"Hallel VeZimrah, Greece List, 1926": "Rast"
						}
					break;
				case JewishCalendar.CHOL_HAMOED_SUCCOS:
					if (jCal.getDayOfWeek() == Calendar.SATURDAY)
						return {
							"Eliahou Yaaqob DWECK-KESAR": "Ashiran",
							"ASHEAR NOTES 1936-1940": "Mahour",
							"ABRAHAM E SHREM ~1945": "Bayat",
							"GABRIEL A SHREM 1964 SUHV": "Bayat",
							"BOZO, Ades, Shir Ushbaha 2005": "Bayat",
							"MOSHE AMASH (Shami)": "Saba",
							"EZRA MASLATON TARAB (Shami)": "Bayat",
							"Hallel VeZimrah, Greece List, 1926": "Bustanigar?"
						};

					return {
						16: {
							"SASSOON #647 Aleppo, 1850": "Sasgar",
							"Eliahou Yaaqob DWECK-KESAR": "Ajam",
							"YAAQOB ABADI-PARSIYA": "Sasgar",
							"YISHAQ YEQAR ARGENTINA": "Ajam",
							"ABRAHAM DWECK Pre1920": "Sasgar",
							"S SAGIR Laniado": "Ajam",
							"ASHEAR list": "Ajam",
							"ASHEAR NOTES 1936-1940": "Ajam",
							"ABRAHAM E SHREM ~1945": "Ajam",
							"Argentina 1947 & Ezra Mishanieh": "Ajam",
							"Shire Zimra H S ABOUD Jerusalem, 1950": "Ajam",
							"GABRIEL A SHREM 1964 SUHV": "Ajam",
							"Ish Massliah \"Abia Renanot\" Tunisians": "Ajam",
							"Shaare Zimra YANANI Buenos Aires, 01": "Ajam",
							"BOZO, Ades, Shir Ushbaha 2005": "Ajam",
							"MOSHE AMASH (Shami)": "Sigah",
							"EZRA MASLATON TARAB (Shami)": "Sigah",
							"ABRAHAM SHAMRICHA (Shami)": "Bayat",
							"Hallel VeZimrah, Greece List, 1926": "Rast"
						}, // Day 2 of Diaspora, but 1st day Hol Hamoed Israel
						17: {
							"SASSOON #647 Aleppo, 1850": "Iraq",
							"Eliahou Yaaqob DWECK-KESAR": "Saba",
							"YAAQOB ABADI-PARSIYA": "Iraq",
							"YISHAQ YEQAR ARGENTINA": "Saba",
							"ASHEAR list": "Iraq",
							"ASHEAR NOTES 1936-1940": "Iraq",
							"Argentina 1947 & Ezra Mishanieh": "Iraq",
							"GABRIEL A SHREM 1964 SUHV": "Iraq"
						},
						18: {
							"SASSOON #647 Aleppo, 1850": "Saba",
							"Eliahou Yaaqob DWECK-KESAR": "Bayat",
							"YAAQOB ABADI-PARSIYA": "Saba",
							"YISHAQ YEQAR ARGENTINA": "Rast",
							"ASHEAR list": "Rast",
							"ASHEAR NOTES 1936-1940": "Rast",
							"Argentina 1947 & Ezra Mishanieh": "Rast",
							"GABRIEL A SHREM 1964 SUHV": "Rast"
						},
						19: {
							"SASSOON #647 Aleppo, 1850": "Rast",
							"Eliahou Yaaqob DWECK-KESAR": "Rast",
							"YAAQOB ABADI-PARSIYA": "Rast",
							"YISHAQ YEQAR ARGENTINA": "Bayat",
							"ASHEAR list": "Nawah",
							"ASHEAR NOTES 1936-1940": "Nawah",
							"Argentina 1947 & Ezra Mishanieh": "Nahwand",
							"GABRIEL A SHREM 1964 SUHV": "Nahwand"
						},
						20: {
							"SASSOON #647 Aleppo, 1850": "Hoseni",
							"Eliahou Yaaqob DWECK-KESAR": "Nawah",
							"YAAQOB ABADI-PARSIYA": "Hoseni",
							"YISHAQ YEQAR ARGENTINA": "Hoseni",
							"ASHEAR list": "Bayat",
							"ASHEAR NOTES 1936-1940": "Bayat",
							"Argentina 1947 & Ezra Mishanieh": "Bayat",
							"GABRIEL A SHREM 1964 SUHV": "Hoseni"
						}
					}[jCal.getJewishDayOfMonth()]!;
					break;
				case JewishCalendar.HOSHANA_RABBA:
					return {
						"SASSOON #647 Aleppo, 1850": "Like Shabbat Shuba",
						"Eliahou Yaaqob DWECK-KESAR": "Hoseni",
						"YAAQOB ABADI-PARSIYA": "Saba",
						"YISHAQ YEQAR ARGENTINA": "Ashiran",
						"ASHEAR list": "Mehayar",
						"ASHEAR NOTES 1936-1940": "Mehayar",
						"Argentina 1947 & Ezra Mishanieh": "Mehayar",
						"GABRIEL A SHREM 1964 SUHV": "Inyan Kippur"
					}
				case JewishCalendar.SHEMINI_ATZERES:
					if (!jCal.getInIsrael()) {
						return {
							"SASSOON #647 Aleppo, 1850": "Ajam",
							"Eliahou Yaaqob DWECK-KESAR": "Ashiran",
							"YAAQOB ABADI-PARSIYA": "Bayat",
							"ABRAHAM DWECK Pre1920": "Bayat",
							"ASHEAR list": "Ajam",
							"ASHEAR NOTES 1936-1940": "Ajam",
							"ABRAHAM E SHREM ~1945": "Saba",
							"Argentina 1947 & Ezra Mishanieh": "Ajam",
							"Shire Zimra H S ABOUD Jerusalem, 1950": "Hoseni",
							"GABRIEL A SHREM 1964 SUHV": "Saba or Sigah",
							"YOSEF YEHEZKEL Jerusalem 1975": "Rast",
							"Ish Massliah \"Abia Renanot\" Tunisians": "Ajam",
							"Shaare Zimra YANANI Buenos Aires, 01": "Saba",
							"BOZO, Ades, Shir Ushbaha 2005": "Saba/Sigah/Hoseni",
							"MOSHE AMASH (Shami)": "Rast",
							"EZRA MASLATON TARAB (Shami)": "Rast",
							"ABRAHAM SHAMRICHA (Shami)": "Rast",
							"Hallel VeZimrah, Greece List, 1926": "Hijaz Kar"
						}
					} else {
						// This data is taken from the Parasha Page on VeZot Haberacha
						return {
							"TABBUSH Ms NLI 8*7622, Aleppo": "Ajam",
							"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Ajam",
							"TEBELE Pre1888": "Ajam",
							"YAAQOB ABADI-PARSIYA": "Ajam",
							"YISHAQ YEQAR ARGENTINA": "Ajam",
							"ADES: 24793": "Ajam",
							"Dibre Shelomo S KASSIN Pre1915": "Ajam",
							"ABRAHAM DWECK Pre1920": "Ajam",
							"IDELSOHN Pre1923": "Ajam",
							"S SAGIR Laniado": "Ajam",
							"M H Elias, SHIR HADASH, Jerusalem, 1930": "Ajam",
							"ASHEAR list": "Ajam",
							"ABRAHAM E SHREM ~1945": "Ajam",
							"Argentina 1947 & Ezra Mishanieh": "Ajam",
							"Shire Zimra H S ABOUD Jerusalem, 1950": "Ajam",
							"GABRIEL A SHREM 1964 SUHV": "Ajam",
							"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Ajam",
							"YOSEF YEHEZKEL Jerusalem 1975": "Ajam",
							"Ish Massliah \"Abia Renanot\" Tunisians": "Ajam",
							"Shaare Zimra YANANI Buenos Aires, 01": "Ajam",
							"BOZO, Ades, Shir Ushbaha 2005": "Ajam",
							"Yishaq Yeranen Halabi": "Ajam",
							"ABRAHAM SHAMRICHA (Shami)": "Bayat"
						}
					}
					break;
				case JewishCalendar.SIMCHAS_TORAH:
					// This data is taken from the Yom Tov Page
					return {
						"SASSOON #647 Aleppo, 1850": "Bayat",
						"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Ajam",
						"Eliahou Yaaqob DWECK-KESAR": "Ajam",
						"YAAQOB ABADI-PARSIYA": "Ajam",
						"YISHAQ YEQAR ARGENTINA": "Ajam",
						"ADES: 24793": "Ajam",
						"Dibre Shelomo S KASSIN Pre1915": "Ajam",
						"ABRAHAM DWECK Pre1920": "Ajam",
						"IDELSOHN Pre1923": "Ajam",
						"S SAGIR Laniado": "Ajam",
						"ASHEAR list": "Saba",
						"ASHEAR NOTES 1936-1940": "Saba",
						"ABRAHAM E SHREM ~1945": "Ajam",
						"Argentina 1947 & Ezra Mishanieh": "Saba",
						"Shire Zimra H S ABOUD Jerusalem, 1950": "Ajam",
						"GABRIEL A SHREM 1964 SUHV": "Ajam",
						"YOSEF YEHEZKEL Jerusalem 1975": "Girka",
						"Ish Massliah \"Abia Renanot\" Tunisians": "Sigah",
						"Shaare Zimra YANANI Buenos Aires, 01": "Ajam",
						"BOZO, Ades, Shir Ushbaha 2005": "Ajam",
						"Yishaq Yeranen Halabi": "Ajam",
						"MOSHE AMASH (Shami)": "Bayat",
						"EZRA MASLATON TARAB (Shami)": "Bayat",
						"ABRAHAM SHAMRICHA (Shami)": "Bayat"
					}
				case JewishCalendar.PURIM:
					return {
						"Eliahou Yaaqob DWECK-KESAR": "Oj / Saba",
						"IDELSOHN Pre1923": "Oj/ Sigah",
						"ASHEAR NOTES 1936-1940": "Sigah",
						"GABRIEL A SHREM 1964 SUHV": "Oj/ Sigah",
						"BOZO, Ades, Shir Ushbaha 2005": "Oj/ Sigah",
						"MOSHE AMASH (Shami)": "Sigah",
						"EZRA MASLATON TARAB (Shami)": "Sigah Rast Day2",
						"ABRAHAM SHAMRICHA (Shami)": "Sigah"
					};
				case JewishCalendar.PESACH:
					return {
						15: {
							"Eliahou Yaaqob DWECK-KESAR": "Sigah",
							"YAAQOB ABADI-PARSIYA": "Sigah",
							"ABRAHAM DWECK Pre1920": "Sigah",
							"IDELSOHN Pre1923": "Bayat",
							"S SAGIR Laniado": "Sigah",
							"ASHEAR list": "Sigah",
							"ASHEAR NOTES 1936-1940": "Sigah",
							"ABRAHAM E SHREM ~1945": "Sigah",
							"Argentina 1947 & Ezra Mishanieh": "Sigah",
							"Shire Zimra H S ABOUD Jerusalem, 1950": "Sigah",
							"GABRIEL A SHREM 1964 SUHV": "Sigah",
							"YOSEF YEHEZKEL Jerusalem 1975": "Sigah",
							"Ish Massliah \"Abia Renanot\" Tunisians": "Sigah",
							"Shaare Zimra YANANI Buenos Aires, 01": "Sigah",
							"BOZO, Ades, Shir Ushbaha 2005": "Sigah/ Bayat",
							"MOSHE AMASH (Shami)": "Rast",
							"EZRA MASLATON TARAB (Shami)": "Rast",
							"ABRAHAM SHAMRICHA (Shami)": "Rast",
							"Hallel VeZimrah, Greece List, 1926": "Sigah"
						},
						16: {
							"Eliahou Yaaqob DWECK-KESAR": "Ajam",
							"YAAQOB ABADI-PARSIYA": "Sasgar",
							"ABRAHAM DWECK Pre1920": "Sasgar",
							"IDELSOHN Pre1923": "Sasgar",
							"S SAGIR Laniado": "Ajam",
							"ASHEAR list": "Ajam",
							"ASHEAR NOTES 1936-1940": "Ajam",
							"ABRAHAM E SHREM ~1945": "Ajam",
							"Argentina 1947 & Ezra Mishanieh": "Ajam",
							"Shire Zimra H S ABOUD Jerusalem, 1950": "Ajam",
							"GABRIEL A SHREM 1964 SUHV": "Ajam",
							"Ish Massliah \"Abia Renanot\" Tunisians": "Ajam",
							"Shaare Zimra YANANI Buenos Aires, 01": "Ajam",
							"BOZO, Ades, Shir Ushbaha 2005": "Ajam-Sasgar",
							"MOSHE AMASH (Shami)": "Sigah",
							"EZRA MASLATON TARAB (Shami)": "Sigah",
							"ABRAHAM SHAMRICHA (Shami)": "Sigah",
							"Hallel VeZimrah, Greece List, 1926": "Ajam"
						},
						21: {
							"Eliahou Yaaqob DWECK-KESAR": "Ajam",
							"YAAQOB ABADI-PARSIYA": "Ajam",
							"ABRAHAM DWECK Pre1920": "Ajam",
							"IDELSOHN Pre1923": "Ajam",
							"S SAGIR Laniado": "Ajam",
							"ASHEAR list": "Ajam",
							"ASHEAR NOTES 1936-1940": "Ajam",
							"ABRAHAM E SHREM ~1945": "Ajam",
							"Argentina 1947 & Ezra Mishanieh": "Ajam",
							"Shire Zimra H S ABOUD Jerusalem, 1950": "Ajam",
							"GABRIEL A SHREM 1964 SUHV": "Ajam",
							"YOSEF YEHEZKEL Jerusalem 1975": "Girkah",
							"Ish Massliah \"Abia Renanot\" Tunisians": "Ajam",
							"Shaare Zimra YANANI Buenos Aires, 01": "Ajam",
							"BOZO, Ades, Shir Ushbaha 2005": "Ajam",
							"MOSHE AMASH (Shami)": "Ajam",
							"EZRA MASLATON TARAB (Shami)": "Ajam",
							"ABRAHAM SHAMRICHA (Shami)": "Ajam",
							"Hallel VeZimrah, Greece List, 1926": "Farahnaq"
						},
						22: {
							"Eliahou Yaaqob DWECK-KESAR": "Ashiran",
							"ABRAHAM DWECK Pre1920": "Bayat",
							"IDELSOHN Pre1923": "Mehayar",
							"S SAGIR Laniado": "Saba",
							"ASHEAR list": "Saba",
							"ASHEAR NOTES 1936-1940": "Saba",
							"ABRAHAM E SHREM ~1945": "Saba",
							"Argentina 1947 & Ezra Mishanieh": "Saba",
							"GABRIEL A SHREM 1964 SUHV": "Saba",
							"Shaare Zimra YANANI Buenos Aires, 01": "Saba",
							"BOZO, Ades, Shir Ushbaha 2005": "Saba/ Mehayar",
							"MOSHE AMASH (Shami)": "Bayat",
							"EZRA MASLATON TARAB (Shami)": "Bayat",
							"Hallel VeZimrah, Greece List, 1926": "Iraq"
						}
					}[jCal.getJewishDayOfMonth()]!;
					break;
				case JewishCalendar.CHOL_HAMOED_PESACH:
					return {
						16: {
							"Eliahou Yaaqob DWECK-KESAR": "Ajam",
							"YAAQOB ABADI-PARSIYA": "Sasgar",
							"ABRAHAM DWECK Pre1920": "Sasgar",
							"IDELSOHN Pre1923": "Sasgar",
							"S SAGIR Laniado": "Ajam",
							"ASHEAR list": "Ajam",
							"ASHEAR NOTES 1936-1940": "Ajam",
							"ABRAHAM E SHREM ~1945": "Ajam",
							"Argentina 1947 & Ezra Mishanieh": "Ajam",
							"Shire Zimra H S ABOUD Jerusalem, 1950": "Ajam",
							"GABRIEL A SHREM 1964 SUHV": "Ajam",
							"Ish Massliah \"Abia Renanot\" Tunisians": "Ajam",
							"Shaare Zimra YANANI Buenos Aires, 01": "Ajam",
							"BOZO, Ades, Shir Ushbaha 2005": "Ajam-Sasgar",
							"MOSHE AMASH (Shami)": "Sigah",
							"EZRA MASLATON TARAB (Shami)": "Sigah",
							"ABRAHAM SHAMRICHA (Shami)": "Sigah",
							"Hallel VeZimrah, Greece List, 1926": "Ajam"
						},
						17: {
							"Eliahou Yaaqob DWECK-KESAR": "Saba",
							"YAAQOB ABADI-PARSIYA": "Iraq",
							"IDELSOHN Pre1923": "Iraq",
							"ASHEAR list": "Iraq",
							"Argentina 1947 & Ezra Mishanieh": "Iraq",
							"GABRIEL A SHREM 1964 SUHV": "Iraq"
						},
						18: {
							"Eliahou Yaaqob DWECK-KESAR": "Bayat",
							"YAAQOB ABADI-PARSIYA": "Rahawi",
							"IDELSOHN Pre1923": "Rahawi",
							"ASHEAR list": "Saba",
							"Argentina 1947 & Ezra Mishanieh": "Saba",
							"GABRIEL A SHREM 1964 SUHV": "Rahawi"
						},
						19: {
							"Eliahou Yaaqob DWECK-KESAR": "Rast",
							"YAAQOB ABADI-PARSIYA": "Rast",
							"IDELSOHN Pre1923": "Rast",
							"ASHEAR list": "Rast",
							"Argentina 1947 & Ezra Mishanieh": "Rast",
							"GABRIEL A SHREM 1964 SUHV": "Rast"
						},
						20: {
							"Eliahou Yaaqob DWECK-KESAR": "Rahawi",
							"YAAQOB ABADI-PARSIYA": "Saba",
							"IDELSOHN Pre1923": "Saba",
							"ASHEAR list": "Bayat",
							"Argentina 1947 & Ezra Mishanieh": "Bayat",
							"GABRIEL A SHREM 1964 SUHV": "Bayat"
						}
					}[jCal.getJewishDayOfMonth()]!;
					break;
				case JewishCalendar.SHAVUOS:
					if (jCal.getJewishDayOfMonth() == 7)
						return {
							"Eliahou Yaaqob DWECK-KESAR": "Ajam",
							"ABRAHAM DWECK Pre1920": "Sasgar",
							"S SAGIR Laniado": "Ajam",
							"ASHEAR list": "Ajam",
							"ASHEAR NOTES 1936-1940": "Ajam",
							"Argentina 1947 & Ezra Mishanieh": "Sasgar",
							"Shire Zimra H S ABOUD Jerusalem, 1950": "Hoseni",
							"GABRIEL A SHREM 1964 SUHV": "Ajam",
							"Ish Massliah \"Abia Renanot\" Tunisians": "Hoseni",
							"Shaare Zimra YANANI Buenos Aires, 01": "Sigah",
							"BOZO, Ades, Shir Ushbaha 2005": "Ajam",
							"MOSHE AMASH (Shami)": "Bayat",
							"EZRA MASLATON TARAB (Shami)": "Bayat",
							"ABRAHAM SHAMRICHA (Shami)": "Bayat",
							"Hallel VeZimrah, Greece List, 1926": "Bustanigar"
						};

					return {
						"Eliahou Yaaqob DWECK-KESAR": "Sigah",
						"ABRAHAM DWECK Pre1920": "Sigah",
						"IDELSOHN Pre1923": "Sigah",
						"S SAGIR Laniado": "Sigah",
						"ASHEAR list": "Sigah",
						"ASHEAR NOTES 1936-1940": "Sigah",
						"Argentina 1947 & Ezra Mishanieh": "Sigah",
						"Shire Zimra H S ABOUD Jerusalem, 1950": "Ajam",
						"GABRIEL A SHREM 1964 SUHV": "Sigah",
						"YOSEF YEHEZKEL Jerusalem 1975": "Bayat Ajam",
						"Ish Massliah \"Abia Renanot\" Tunisians": "Ajam",
						"Shaare Zimra YANANI Buenos Aires, 01": "Ajam",
						"BOZO, Ades, Shir Ushbaha 2005": "Sigah",
						"MOSHE AMASH (Shami)": "Rast",
						"EZRA MASLATON TARAB (Shami)": "Rast",
						"ABRAHAM SHAMRICHA (Shami)": "Rast",
						"Hallel VeZimrah, Greece List, 1926": "Rast"
					};
			}
		}

		const data:Partial<Record<Parsha, Partial<Record<Unpacked<typeof entries>, string>>>> = {
			[Parsha.BERESHIS]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Rast",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Rast / Bayat",
				"TEBELE Pre1888": "Rast",
				"YAAQOB ABADI-PARSIYA": "Rast",
				"YISHAQ YEQAR ARGENTINA": "Rast",
				"ADES: 24793": "Rast",
				"Dibre Shelomo S KASSIN Pre1915": "Rast / Bayat",
				"Knis Betesh Geniza List, Aleppo": "Rast",
				"ABRAHAM DWECK Pre1920": "Rast",
				"IDELSOHN Pre1923": "Rast",
				"S SAGIR Laniado": "Rast",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Rast",
				"ASHEAR list": "Rast",
				"ASHEAR NOTES 1936-1940": "Rast",
				"ABRAHAM E SHREM ~1945": "Rast",
				"Argentina 1947 & Ezra Mishanieh": "Rast",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Bayat / Rast",
				"GABRIEL A SHREM 1964 SUHV": "Rast",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Rast",
				"YOSEF YEHEZKEL Jerusalem 1975": "Rast",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Rast",
				"Shaare Zimra YANANI Buenos Aires, 01": "Rast",
				"BOZO, Ades, Shir Ushbaha 2005": "Rast",
				"Yishaq Yeranen Halabi": "Rast",
				"MOSHE AMASH (Shami)": "Rast",
				"EZRA MASLATON TARAB (Shami)": "Rast",
				"ABRAHAM SHAMRICHA (Shami)": "Rast",
				"Victor Afya, Istanbul List": "Segah",
				"Izak Alaluf, Izmir List": "Segah",
				"Hallel VeZimrah, Salonika, 1928": "Rast"
			},
			[Parsha.NOACH]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Iraq",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Iraq / Saba",
				"TEBELE Pre1888": "Iraq",
				"YAAQOB ABADI-PARSIYA": "Bayat",
				"YISHAQ YEQAR ARGENTINA": "Iraq",
				"ADES: 24793": "Iraq/ Saba",
				"Dibre Shelomo S KASSIN Pre1915": "Iraq / Saba",
				"Knis Betesh Geniza List, Aleppo": "Iraq / Sigah",
				"ABRAHAM DWECK Pre1920": "Sigah",
				"IDELSOHN Pre1923": "Iraq",
				"S SAGIR Laniado": "Bayat",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Sigah",
				"ASHEAR list": "Iraq",
				"ASHEAR NOTES 1936-1940": "Iraq / Sigah",
				"ABRAHAM E SHREM ~1945": "Sigah",
				"Argentina 1947 & Ezra Mishanieh": "Iraq",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Iraq / Bayat",
				"GABRIEL A SHREM 1964 SUHV": "Sigah",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Sigah",
				"YOSEF YEHEZKEL Jerusalem 1975": "Hijaz",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Hijaz",
				"Shaare Zimra YANANI Buenos Aires, 01": "Bayat",
				"BOZO, Ades, Shir Ushbaha 2005": "Bayat / Sigah",
				"Yishaq Yeranen Halabi": "Bayat",
				"MOSHE AMASH (Shami)": "Nawah",
				"EZRA MASLATON TARAB (Shami)": "Nawah",
				"ABRAHAM SHAMRICHA (Shami)": "Nawah",
				"Victor Afya, Istanbul List": "Hicaz",
				"Izak Alaluf, Izmir List": "Hicaz",
				"Hallel VeZimrah, Salonika, 1928": "Nibah"
			},
			[Parsha.LECH_LECHA]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Saba",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Saba",
				"TEBELE Pre1888": "Saba",
				"YAAQOB ABADI-PARSIYA": "Saba",
				"YISHAQ YEQAR ARGENTINA": "Saba",
				"ADES: 24793": "Saba",
				"Dibre Shelomo S KASSIN Pre1915": "Saba",
				"Knis Betesh Geniza List, Aleppo": "Saba",
				"ABRAHAM DWECK Pre1920": "Saba",
				"IDELSOHN Pre1923": "Saba",
				"S SAGIR Laniado": "Saba",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Saba",
				"ASHEAR list": "Saba",
				"ASHEAR NOTES 1936-1940": "Saba",
				"ABRAHAM E SHREM ~1945": "Saba",
				"Argentina 1947 & Ezra Mishanieh": "Saba",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Saba",
				"GABRIEL A SHREM 1964 SUHV": "Saba",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Saba",
				"YOSEF YEHEZKEL Jerusalem 1975": "Saba",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Saba",
				"Shaare Zimra YANANI Buenos Aires, 01": "Saba",
				"BOZO, Ades, Shir Ushbaha 2005": "Saba",
				"Yishaq Yeranen Halabi": "Saba",
				"MOSHE AMASH (Shami)": "Sigah / Iraq",
				"EZRA MASLATON TARAB (Shami)": "Sigah / Iraq",
				"ABRAHAM SHAMRICHA (Shami)": "Sigah",
				"Victor Afya, Istanbul List": "Huseyni",
				"Izak Alaluf, Izmir List": "Huseyni",
				"Hallel VeZimrah, Salonika, 1928": "Nahoft"
			},
			[Parsha.VAYERA]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Hijaz",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Hijaz",
				"TEBELE Pre1888": "Hijaz",
				"YAAQOB ABADI-PARSIYA": "Hijaz",
				"YISHAQ YEQAR ARGENTINA": "Hijaz",
				"ADES: 24793": "Arazbar",
				"Dibre Shelomo S KASSIN Pre1915": "Hijaz Arazbar",
				"Knis Betesh Geniza List, Aleppo": "Hijaz",
				"ABRAHAM DWECK Pre1920": "Hijaz",
				"IDELSOHN Pre1923": "Hijaz",
				"S SAGIR Laniado": "Hijaz",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Hijaz",
				"ASHEAR list": "Hijaz",
				"ASHEAR NOTES 1936-1940": "Hijaz",
				"ABRAHAM E SHREM ~1945": "Hijaz",
				"Argentina 1947 & Ezra Mishanieh": "Hijaz",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Hijaz",
				"GABRIEL A SHREM 1964 SUHV": "Hijaz",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Nahwand",
				"YOSEF YEHEZKEL Jerusalem 1975": "Hijaz Kar",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Hijaz Kar",
				"Shaare Zimra YANANI Buenos Aires, 01": "Nahwand",
				"BOZO, Ades, Shir Ushbaha 2005": "Hijaz",
				"Yishaq Yeranen Halabi": "Hijaz",
				"MOSHE AMASH (Shami)": "Saba",
				"EZRA MASLATON TARAB (Shami)": "Saba",
				"ABRAHAM SHAMRICHA (Shami)": "Saba",
				"Victor Afya, Istanbul List": "Dugah",
				"Izak Alaluf, Izmir List": "Dugah",
				"Hallel VeZimrah, Salonika, 1928": "Bustanigar"
			},
			[Parsha.CHAYEI_SARA]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Hijaz",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Hijaz",
				"TEBELE Pre1888": "Hijaz",
				"YAAQOB ABADI-PARSIYA": "Hijaz",
				"YISHAQ YEQAR ARGENTINA": "Hijaz",
				"ADES: 24793": "Arazbar",
				"Dibre Shelomo S KASSIN Pre1915": "Hijaz Arazbar",
				"Knis Betesh Geniza List, Aleppo": "Hijaz",
				"ABRAHAM DWECK Pre1920": "Hijaz",
				"IDELSOHN Pre1923": "Hijaz",
				"S SAGIR Laniado": "Hijaz",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Hijaz",
				"ASHEAR list": "Hijaz",
				"ASHEAR NOTES 1936-1940": "Hijaz",
				"ABRAHAM E SHREM ~1945": "Hijaz",
				"Argentina 1947 & Ezra Mishanieh": "Hijaz",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Hijaz",
				"GABRIEL A SHREM 1964 SUHV": "Hijaz",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Nahwand",
				"YOSEF YEHEZKEL Jerusalem 1975": "Hijaz Kar",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Hijaz Kar",
				"Shaare Zimra YANANI Buenos Aires, 01": "Nahwand",
				"BOZO, Ades, Shir Ushbaha 2005": "Hijaz",
				"Yishaq Yeranen Halabi": "Hijaz",
				"MOSHE AMASH (Shami)": "Saba",
				"EZRA MASLATON TARAB (Shami)": "Saba",
				"ABRAHAM SHAMRICHA (Shami)": "Saba",
				"Victor Afya, Istanbul List": "Dugah",
				"Izak Alaluf, Izmir List": "Dugah",
				"Hallel VeZimrah, Salonika, 1928": "Bustanigar"
			},
			[Parsha.TOLDOS]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Mahour",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Mahour",
				"TEBELE Pre1888": "Mahour",
				"YAAQOB ABADI-PARSIYA": "Mahour",
				"YISHAQ YEQAR ARGENTINA": "Mahour",
				"ADES: 24793": "Mahour",
				"Dibre Shelomo S KASSIN Pre1915": "Mahour",
				"Knis Betesh Geniza List, Aleppo": "Rast",
				"ABRAHAM DWECK Pre1920": "Rast",
				"IDELSOHN Pre1923": "Mahour",
				"S SAGIR Laniado": "Mahour",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Mahour",
				"ASHEAR list": "Mahour",
				"ASHEAR NOTES 1936-1940": "Mahour",
				"ABRAHAM E SHREM ~1945": "Mahour",
				"Argentina 1947 & Ezra Mishanieh": "Mahour",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Mahour",
				"GABRIEL A SHREM 1964 SUHV": "Mahour",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Rast",
				"YOSEF YEHEZKEL Jerusalem 1975": "Mahour",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Mahour",
				"Shaare Zimra YANANI Buenos Aires, 01": "Rast",
				"BOZO, Ades, Shir Ushbaha 2005": "Mahour",
				"Yishaq Yeranen Halabi": "Mahour",
				"MOSHE AMASH (Shami)": "Rast",
				"EZRA MASLATON TARAB (Shami)": "Mahour",
				"ABRAHAM SHAMRICHA (Shami)": "Mahour",
				"Victor Afya, Istanbul List": "Mahur",
				"Izak Alaluf, Izmir List": "Araban",
				"Hallel VeZimrah, Salonika, 1928": "Iraq"
			},
			[Parsha.VAYETZEI]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Sharga",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Girka",
				"TEBELE Pre1888": "Girka",
				"YAAQOB ABADI-PARSIYA": "Girka",
				"YISHAQ YEQAR ARGENTINA": "Girka",
				"ADES: 24793": "Girka",
				"Dibre Shelomo S KASSIN Pre1915": "Girka- Ajam",
				"Knis Betesh Geniza List, Aleppo": "Saba",
				"ABRAHAM DWECK Pre1920": "Saba",
				"IDELSOHN Pre1923": "Girka",
				"S SAGIR Laniado": "Ajam",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Saba",
				"ASHEAR list": "Sharga",
				"ASHEAR NOTES 1936-1940": "Ajam",
				"ABRAHAM E SHREM ~1945": "Saba",
				"Argentina 1947 & Ezra Mishanieh": "Girka, Sharga",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Ajam",
				"GABRIEL A SHREM 1964 SUHV": "Ajam",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Saba",
				"YOSEF YEHEZKEL Jerusalem 1975": "Ajam",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Ajam",
				"Shaare Zimra YANANI Buenos Aires, 01": "Ajam",
				"BOZO, Ades, Shir Ushbaha 2005": "Ajam",
				"Yishaq Yeranen Halabi": "Ajam",
				"MOSHE AMASH (Shami)": "Ajam",
				"EZRA MASLATON TARAB (Shami)": "Ajam",
				"ABRAHAM SHAMRICHA (Shami)": "Ajam",
				"Victor Afya, Istanbul List": "Nihavend",
				"Izak Alaluf, Izmir List": "Beyati",
				"Hallel VeZimrah, Salonika, 1928": "Saba"
			},
			[Parsha.VAYISHLACH]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Iraq",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Iraq/ Saba",
				"TEBELE Pre1888": "Iraq",
				"YAAQOB ABADI-PARSIYA": "Bayat",
				"YISHAQ YEQAR ARGENTINA": "Sigah",
				"ADES: 24793": "Iraq/ Saba",
				"Dibre Shelomo S KASSIN Pre1915": "Iraq or Saba",
				"Knis Betesh Geniza List, Aleppo": "Iraq",
				"ABRAHAM DWECK Pre1920": "Bayat",
				"IDELSOHN Pre1923": "Iraq",
				"S SAGIR Laniado": "Bayat",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Hoseni",
				"ASHEAR list": "Iraq",
				"ASHEAR NOTES 1936-1940": "Sigah-Iraq",
				"ABRAHAM E SHREM ~1945": "Hoseni",
				"Argentina 1947 & Ezra Mishanieh": "Iraq",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Saba / Sigah",
				"GABRIEL A SHREM 1964 SUHV": "Saba / Sigah",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Sigah",
				"YOSEF YEHEZKEL Jerusalem 1975": "Saba",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Saba",
				"Shaare Zimra YANANI Buenos Aires, 01": "Bayat",
				"BOZO, Ades, Shir Ushbaha 2005": "Bayat / Sigah",
				"Yishaq Yeranen Halabi": "Bayat",
				"MOSHE AMASH (Shami)": "Bayat",
				"EZRA MASLATON TARAB (Shami)": "Bayat",
				"ABRAHAM SHAMRICHA (Shami)": "Bayat",
				"Victor Afya, Istanbul List": "Acem Ashiran",
				"Izak Alaluf, Izmir List": "Acem Ashiran",
				"Hallel VeZimrah, Salonika, 1928": "Huzam"
			},
			[Parsha.VAYESHEV]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Rahaw",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Rahawi",
				"TEBELE Pre1888": "Rahawi",
				"YAAQOB ABADI-PARSIYA": "Rahawi",
				"YISHAQ YEQAR ARGENTINA": "Rahawi",
				"ADES: 24793": "Rahaw",
				"Dibre Shelomo S KASSIN Pre1915": "Rahaw",
				"Knis Betesh Geniza List, Aleppo": "Rahaw",
				"ABRAHAM DWECK Pre1920": "",
				"IDELSOHN Pre1923": "Rahawi",
				"S SAGIR Laniado": "Nawah",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Rahaw",
				"ASHEAR list": "Rahaw",
				"ASHEAR NOTES 1936-1940": "Nawah-Nahwand",
				"ABRAHAM E SHREM ~1945": "Rahaw / Nahwand",
				"Argentina 1947 & Ezra Mishanieh": "Rahaw",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Rahawi",
				"GABRIEL A SHREM 1964 SUHV": "Rahawi/ Nahwand",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Nawah",
				"YOSEF YEHEZKEL Jerusalem 1975": "Nahwand",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Nahwand",
				"Shaare Zimra YANANI Buenos Aires, 01": "Nawah",
				"BOZO, Ades, Shir Ushbaha 2005": "Rahawi-Nawah",
				"Yishaq Yeranen Halabi": "Nawah",
				"MOSHE AMASH (Shami)": "Nawah",
				"EZRA MASLATON TARAB (Shami)": "Nawah",
				"ABRAHAM SHAMRICHA (Shami)": "Nawah",
				"Victor Afya, Istanbul List": "Ussak",
				"Izak Alaluf, Izmir List": "Isfahan",
				"Hallel VeZimrah, Salonika, 1928": "Sigah"
			},
			[Parsha.MIKETZ]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Sigah",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Sigah",
				"TEBELE Pre1888": "Sigah",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Sigah",
				"YAAQOB ABADI-PARSIYA": "Sigah",
				"YISHAQ YEQAR ARGENTINA": "Sigah",
				"ADES: 24793": "Sigah",
				"Dibre Shelomo S KASSIN Pre1915": "Sigah",
				"Knis Betesh Geniza List, Aleppo": "Sigah",
				"ABRAHAM DWECK Pre1920": "Sigah",
				"IDELSOHN Pre1923": "Sigah",
				"S SAGIR Laniado": "Sigah",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Sigah",
				"ASHEAR list": "Sigah",
				"ASHEAR NOTES 1936-1940": "Sigah",
				"ABRAHAM E SHREM ~1945": "Sigah",
				"Argentina 1947 & Ezra Mishanieh": "Sigah",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Sigah",
				"GABRIEL A SHREM 1964 SUHV": "Sigah",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Sigah",
				"YOSEF YEHEZKEL Jerusalem 1975": "Sigah",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Sigah",
				"Shaare Zimra YANANI Buenos Aires, 01": "Sigah",
				"BOZO, Ades, Shir Ushbaha 2005": "Sigah",
				"Yishaq Yeranen Halabi": "Sigah",
				"MOSHE AMASH (Shami)": "Rahawi",
				"EZRA MASLATON TARAB (Shami)": "Rahawi",
				"ABRAHAM SHAMRICHA (Shami)": "Rahawi",
				"Victor Afya, Istanbul List": "",
				"Izak Alaluf, Izmir List": "Ussak",
				"Hallel VeZimrah, Salonika, 1928": "Ussak"
			},
			[Parsha.VAYIGASH]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Bayat",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Bayat",
				"TEBELE Pre1888": "Bayat",
				"YAAQOB ABADI-PARSIYA": "Saba",
				"YISHAQ YEQAR ARGENTINA": "Bayat",
				"ADES: 24793": "Bayat",
				"Dibre Shelomo S KASSIN Pre1915": "Bayat",
				"Knis Betesh Geniza List, Aleppo": "Saba",
				"ABRAHAM DWECK Pre1920": "Saba",
				"IDELSOHN Pre1923": "Bayat",
				"S SAGIR Laniado": "Saba",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Mahour",
				"ASHEAR list": "Bayat",
				"ASHEAR NOTES 1936-1940": "Bayat",
				"ABRAHAM E SHREM ~1945": "Mahour",
				"Argentina 1947 & Ezra Mishanieh": "Bayat",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Bayat / Saba",
				"GABRIEL A SHREM 1964 SUHV": "Bayat",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Bayat",
				"YOSEF YEHEZKEL Jerusalem 1975": "Bayat",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Bayat",
				"BOZO, Ades, Shir Ushbaha 2005": "Bayat",
				"Yishaq Yeranen Halabi": "Bayat / Saba",
				"MOSHE AMASH (Shami)": "Sigah",
				"EZRA MASLATON TARAB (Shami)": "Sigah",
				"ABRAHAM SHAMRICHA (Shami)": "Sigah",
				"Victor Afya, Istanbul List": "Segah",
				"Izak Alaluf, Izmir List": "Nihavend",
				"Hallel VeZimrah, Salonika, 1928": "Muhayer"
			},
			[Parsha.VAYECHI]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Hijaz",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Hijaz",
				"TEBELE Pre1888": "Hijaz",
				"YAAQOB ABADI-PARSIYA": "Hijaz",
				"YISHAQ YEQAR ARGENTINA": "Hijaz",
				"ADES: 24793": "Hijaz",
				"Dibre Shelomo S KASSIN Pre1915": "Hijaz",
				"Knis Betesh Geniza List, Aleppo": "Hijaz",
				"ABRAHAM DWECK Pre1920": "Hijaz",
				"IDELSOHN Pre1923": "Hijaz",
				"S SAGIR Laniado": "Hijaz",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Hijaz",
				"ASHEAR list": "Hijaz",
				"ASHEAR NOTES 1936-1940": "Hijaz",
				"ABRAHAM E SHREM ~1945": "Hijaz",
				"Argentina 1947 & Ezra Mishanieh": "Hijaz",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Hijaz",
				"GABRIEL A SHREM 1964 SUHV": "Hijaz",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Nahwand",
				"YOSEF YEHEZKEL Jerusalem 1975": "Shuri",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Hijaz",
				"Shaare Zimra YANANI Buenos Aires, 01": "Nahwand",
				"BOZO, Ades, Shir Ushbaha 2005": "Hijaz",
				"Yishaq Yeranen Halabi": "Hijaz",
				"MOSHE AMASH (Shami)": "Saba",
				"EZRA MASLATON TARAB (Shami)": "Saba",
				"ABRAHAM SHAMRICHA (Shami)": "Saba",
				"Victor Afya, Istanbul List": "Beyati",
				"Izak Alaluf, Izmir List": "Cargah",
				"Hallel VeZimrah, Salonika, 1928": "Ajam"
			},
			[Parsha.SHEMOS]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Rast",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Bayat / Rast",
				"TEBELE Pre1888": "Bayat",
				"YAAQOB ABADI-PARSIYA": "Bayat",
				"YISHAQ YEQAR ARGENTINA": "Rast",
				"ADES: 24793": "Bayat/ Rast",
				"Dibre Shelomo S KASSIN Pre1915": "Bayat / Rast",
				"Knis Betesh Geniza List, Aleppo": "Rast",
				"ABRAHAM DWECK Pre1920": "Rast",
				"IDELSOHN Pre1923": "Rast",
				"S SAGIR Laniado": "Bayat",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Hoseni",
				"ASHEAR list": "Rast Bayat",
				"ASHEAR NOTES 1936-1940": "Bayat / Rast",
				"ABRAHAM E SHREM ~1945": "Hoseni",
				"Argentina 1947 & Ezra Mishanieh": "Bayat / Rast",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Bayat / Rast",
				"GABRIEL A SHREM 1964 SUHV": "Rast or Bayat",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Rast",
				"YOSEF YEHEZKEL Jerusalem 1975": "Rast",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Rast",
				"Shaare Zimra YANANI Buenos Aires, 01": "Rast",
				"BOZO, Ades, Shir Ushbaha 2005": "Bayat / Rast",
				"Yishaq Yeranen Halabi": "Bayat",
				"MOSHE AMASH (Shami)": "Rast",
				"EZRA MASLATON TARAB (Shami)": "Rast",
				"ABRAHAM SHAMRICHA (Shami)": "Rast",
				"Victor Afya, Istanbul List": "Nihavend",
				"Izak Alaluf, Izmir List": "Nihavend",
				"Hallel VeZimrah, Greece List, 1926": "Bayati"
			},
			[Parsha.VAERA]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Saba",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Hoseni / Nawah",
				"TEBELE Pre1888": "Hoseni",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Iraq / Hoseni / Nawah",
				"YAAQOB ABADI-PARSIYA": "Iraq / Hoseni",
				"YISHAQ YEQAR ARGENTINA": "Sigah",
				"ADES: 24793": "Hoseni / Nawah",
				"Dibre Shelomo S KASSIN Pre1915": "Hoseni / Nawah",
				"Knis Betesh Geniza List, Aleppo": "Bayat",
				"ABRAHAM DWECK Pre1920": "Bayat",
				"IDELSOHN Pre1923": "Hoseni/ Nawah",
				"S SAGIR Laniado": "Sigah",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Saba",
				"ASHEAR list": "Sigah",
				"ASHEAR NOTES 1936-1940": "Nahwand / Bayat",
				"ABRAHAM E SHREM ~1945": "Saba",
				"Argentina 1947 & Ezra Mishanieh": "Sigah",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Hoseni / Sigah",
				"GABRIEL A SHREM 1964 SUHV": "Hoseni or Rast",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Bayat",
				"YOSEF YEHEZKEL Jerusalem 1975": "Hoseni",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Bayat",
				"Shaare Zimra YANANI Buenos Aires, 01": "Sigah",
				"BOZO, Ades, Shir Ushbaha 2005": "Nawah / Hoseni",
				"Yishaq Yeranen Halabi": "Nawah",
				"MOSHE AMASH (Shami)": "Bayat",
				"EZRA MASLATON TARAB (Shami)": "Bayat",
				"ABRAHAM SHAMRICHA (Shami)": "Bayat",
				"Victor Afya, Istanbul List": "Hicaz",
				"Izak Alaluf, Izmir List": "Hicaz",
				"Hallel VeZimrah, Greece List, 1926": "Busaliq"
			},
			[Parsha.BO]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Iraq",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Iraq / Rast",
				"TEBELE Pre1888": "Iraq",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Rast / Iraq",
				"YAAQOB ABADI-PARSIYA": "Rast / Sigah",
				"YISHAQ YEQAR ARGENTINA": "Bayat",
				"ADES: 24793": "Iraq/ Rast",
				"Dibre Shelomo S KASSIN Pre1915": "Iraq / Rast",
				"Knis Betesh Geniza List, Aleppo": "Saba",
				"ABRAHAM DWECK Pre1920": "Rahaw",
				"IDELSOHN Pre1923": "Iraq",
				"S SAGIR Laniado": "Rast",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Bayat",
				"ASHEAR list": "Rast",
				"ASHEAR NOTES 1936-1940": "Nawah-Nahwand",
				"ABRAHAM E SHREM ~1945": "Nahwand",
				"Argentina 1947 & Ezra Mishanieh": "Rast",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Sigah / Rast",
				"GABRIEL A SHREM 1964 SUHV": "Sigah",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Sigah",
				"YOSEF YEHEZKEL Jerusalem 1975": "Sigah",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Sigah",
				"Shaare Zimra YANANI Buenos Aires, 01": "Nawah",
				"BOZO, Ades, Shir Ushbaha 2005": "Sigah",
				"Yishaq Yeranen Halabi": "Sigah",
				"MOSHE AMASH (Shami)": "Rast",
				"EZRA MASLATON TARAB (Shami)": "Rahawi",
				"ABRAHAM SHAMRICHA (Shami)": "Nawah",
				"Victor Afya, Istanbul List": "Huseyni",
				"Izak Alaluf, Izmir List": "Huseyni",
				"Hallel VeZimrah, Greece List, 1926": "Qargigar"
			},
			[Parsha.BESHALACH]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Ajam",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Ajam",
				"TEBELE Pre1888": "Ajam",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Ajam",
				"YAAQOB ABADI-PARSIYA": "Ajam",
				"YISHAQ YEQAR ARGENTINA": "Ajam",
				"ADES: 24793": "Ajam",
				"Dibre Shelomo S KASSIN Pre1915": "Ajam",
				"Knis Betesh Geniza List, Aleppo": "Ajam",
				"ABRAHAM DWECK Pre1920": "Ajam",
				"IDELSOHN Pre1923": "Ajam",
				"S SAGIR Laniado": "Ajam",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Ajam",
				"ASHEAR list": "Ajam",
				"ASHEAR NOTES 1936-1940": "Ajam",
				"ABRAHAM E SHREM ~1945": "Ajam",
				"Argentina 1947 & Ezra Mishanieh": "Ajam",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Ajam",
				"GABRIEL A SHREM 1964 SUHV": "Ajam",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Ajam",
				"YOSEF YEHEZKEL Jerusalem 1975": "Ajam",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Ajam",
				"Shaare Zimra YANANI Buenos Aires, 01": "Ajam",
				"BOZO, Ades, Shir Ushbaha 2005": "Ajam",
				"Yishaq Yeranen Halabi": "Ajam",
				"MOSHE AMASH (Shami)": "Ajam",
				"EZRA MASLATON TARAB (Shami)": "Ajam",
				"ABRAHAM SHAMRICHA (Shami)": "Ajam",
				"Victor Afya, Istanbul List": "Acem Ashiran",
				"Izak Alaluf, Izmir List": "Acem Ashiran",
				"Hallel VeZimrah, Greece List, 1926": "Farahnq?"
			},
			[Parsha.YISRO]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Hoseni",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Hoseni",
				"TEBELE Pre1888": "Hoseni",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "(Hoseni)",
				"YAAQOB ABADI-PARSIYA": "Hoseni",
				"YISHAQ YEQAR ARGENTINA": "Hoseni",
				"ADES: 24793": "Hoseni",
				"Dibre Shelomo S KASSIN Pre1915": "Hoseni",
				"Knis Betesh Geniza List, Aleppo": "Hoseni",
				"ABRAHAM DWECK Pre1920": "Hoseni",
				"IDELSOHN Pre1923": "Sigah",
				"S SAGIR Laniado": "Hoseni",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Hoseni",
				"ASHEAR list": "Hoseni",
				"ASHEAR NOTES 1936-1940": "Hoseni",
				"ABRAHAM E SHREM ~1945": "Hoseni",
				"Argentina 1947 & Ezra Mishanieh": "Hoseni",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Hoseni",
				"GABRIEL A SHREM 1964 SUHV": "Hoseni",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Bayat",
				"YOSEF YEHEZKEL Jerusalem 1975": "Kurd",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Kurd Hoseni",
				"Shaare Zimra YANANI Buenos Aires, 01": "Bayat",
				"BOZO, Ades, Shir Ushbaha 2005": "Hoseni / Sigah",
				"Yishaq Yeranen Halabi": "Hoseni",
				"MOSHE AMASH (Shami)": "Bayat",
				"EZRA MASLATON TARAB (Shami)": "Bayat",
				"ABRAHAM SHAMRICHA (Shami)": "Bayat",
				"Victor Afya, Istanbul List": "Mahur or Sehnaz",
				"Izak Alaluf, Izmir List": "Mahur",
				"Hallel VeZimrah, Greece List, 1926": "Rast"
			},
			[Parsha.MISHPATIM]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Nawah",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Saba / Rast",
				"TEBELE Pre1888": "Saba",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Nawah / Saba",
				"YAAQOB ABADI-PARSIYA": "Nawah / Saba",
				"YISHAQ YEQAR ARGENTINA": "Nawah",
				"ADES: 24793": "Saba",
				"Dibre Shelomo S KASSIN Pre1915": "Saba",
				"Knis Betesh Geniza List, Aleppo": "Nawah",
				"ABRAHAM DWECK Pre1920": "Nahwand",
				"IDELSOHN Pre1923": "Saba",
				"S SAGIR Laniado": "Nawah",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Saba / Rast",
				"ASHEAR list": "Nawah",
				"ASHEAR NOTES 1936-1940": "Bayat / Nawah",
				"ABRAHAM E SHREM ~1945": "Rast",
				"Argentina 1947 & Ezra Mishanieh": "Nahwand",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Saba",
				"GABRIEL A SHREM 1964 SUHV": "Saba",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Saba",
				"YOSEF YEHEZKEL Jerusalem 1975": "Saba / Isfahan",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Saba",
				"Shaare Zimra YANANI Buenos Aires, 01": "Rast",
				"BOZO, Ades, Shir Ushbaha 2005": "Saba",
				"Yishaq Yeranen Halabi": "Saba",
				"MOSHE AMASH (Shami)": "Sigah",
				"EZRA MASLATON TARAB (Shami)": "Sigah",
				"ABRAHAM SHAMRICHA (Shami)": "Sigah",
				"Victor Afya, Istanbul List": "Araban",
				"Izak Alaluf, Izmir List": "Beyati",
				"Hallel VeZimrah, Greece List, 1926": "Nibah"
			},
			[Parsha.TERUMAH]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Saba",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Saba",
				"TEBELE Pre1888": "Saba",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Saba / Rast",
				"YAAQOB ABADI-PARSIYA": "Rast / Saba",
				"YISHAQ YEQAR ARGENTINA": "Saba",
				"ADES: 24793": "Saba",
				"Dibre Shelomo S KASSIN Pre1915": "Saba Mouhayar",
				"Knis Betesh Geniza List, Aleppo": "Saba",
				"ABRAHAM DWECK Pre1920": "Saba",
				"IDELSOHN Pre1923": "Sigah",
				"S SAGIR Laniado": "Saba",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Hoseni / Saba",
				"ASHEAR list": "Saba",
				"ASHEAR NOTES 1936-1940": "Bayat",
				"ABRAHAM E SHREM ~1945": "Saba",
				"Argentina 1947 & Ezra Mishanieh": "Saba",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Bayat / Saba",
				"GABRIEL A SHREM 1964 SUHV": "Hoseni",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Rast",
				"YOSEF YEHEZKEL Jerusalem 1975": "Bayat/ Hoseni",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Bayat",
				"Shaare Zimra YANANI Buenos Aires, 01": "Saba",
				"BOZO, Ades, Shir Ushbaha 2005": "Bayat / Sigah",
				"Yishaq Yeranen Halabi": "Bayat",
				"MOSHE AMASH (Shami)": "Rast",
				"EZRA MASLATON TARAB (Shami)": "Bayat",
				"ABRAHAM SHAMRICHA (Shami)": "Bayat",
				"Victor Afya, Istanbul List": "Beyati",
				"Izak Alaluf, Izmir List": "Segah",
				"Hallel VeZimrah, Greece List, 1926": "Nahawand"
			},
			[Parsha.TETZAVEH]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Sigah",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Sigah",
				"TEBELE Pre1888": "Sigah",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Sigah",
				"YAAQOB ABADI-PARSIYA": "Sigah",
				"YISHAQ YEQAR ARGENTINA": "Sigah",
				"ADES: 24793": "Sigah",
				"Dibre Shelomo S KASSIN Pre1915": "Sigah",
				"Knis Betesh Geniza List, Aleppo": "Sigah",
				"ABRAHAM DWECK Pre1920": "Sigah",
				"IDELSOHN Pre1923": "Sigah",
				"S SAGIR Laniado": "Sigah",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Saba Sigah",
				"ASHEAR list": "Sigah",
				"ASHEAR NOTES 1936-1940": "Sigah",
				"ABRAHAM E SHREM ~1945": "Sigah",
				"Argentina 1947 & Ezra Mishanieh": "Sigah",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Sigah",
				"GABRIEL A SHREM 1964 SUHV": "Sigah",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Sigah",
				"YOSEF YEHEZKEL Jerusalem 1975": "Sigah",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Sigah",
				"Shaare Zimra YANANI Buenos Aires, 01": "Sigah",
				"BOZO, Ades, Shir Ushbaha 2005": "Sigah",
				"Yishaq Yeranen Halabi": "Sigah",
				"MOSHE AMASH (Shami)": "Bayat",
				"EZRA MASLATON TARAB (Shami)": "Mahour",
				"ABRAHAM SHAMRICHA (Shami)": "Mahour",
				"Victor Afya, Istanbul List": "Segah",
				"Izak Alaluf, Izmir List": "Isfahan",
				"Hallel VeZimrah, Greece List, 1926": "Sigah?"
			},
			[Parsha.KI_SISA]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Hijaz",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Hijaz",
				"TEBELE Pre1888": "Hijaz",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Hijaz",
				"YAAQOB ABADI-PARSIYA": "Hijaz",
				"YISHAQ YEQAR ARGENTINA": "Hijaz",
				"ADES: 24793": "Hijaz",
				"Dibre Shelomo S KASSIN Pre1915": "Hijaz",
				"Knis Betesh Geniza List, Aleppo": "Hijaz",
				"ABRAHAM DWECK Pre1920": "Hijaz",
				"IDELSOHN Pre1923": "Hijaz",
				"S SAGIR Laniado": "Hijaz",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Hijaz",
				"ASHEAR list": "Hijaz",
				"ASHEAR NOTES 1936-1940": "Hijaz",
				"ABRAHAM E SHREM ~1945": "Hijaz",
				"Argentina 1947 & Ezra Mishanieh": "Hijaz",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Hijaz",
				"GABRIEL A SHREM 1964 SUHV": "Hijaz",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Nahwand",
				"YOSEF YEHEZKEL Jerusalem 1975": "Shuri",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Hijaz",
				"Shaare Zimra YANANI Buenos Aires, 01": "Nahwand",
				"BOZO, Ades, Shir Ushbaha 2005": "Hijaz",
				"Yishaq Yeranen Halabi": "Hijaz",
				"MOSHE AMASH (Shami)": "Saba",
				"EZRA MASLATON TARAB (Shami)": "Saba",
				"ABRAHAM SHAMRICHA (Shami)": "Saba",
				"Victor Afya, Istanbul List": "Hicaz",
				"Izak Alaluf, Izmir List": "Araban",
				"Hallel VeZimrah, Greece List, 1926": "Haqaqordo?"
			},
			[Parsha.VAYAKHEL]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Hoseni",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Hoseni",
				"TEBELE Pre1888": "Hoseni",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Hoseni",
				"YAAQOB ABADI-PARSIYA": "Hoseni",
				"YISHAQ YEQAR ARGENTINA": "Saba",
				"ADES: 24793": "Hoseni",
				"Dibre Shelomo S KASSIN Pre1915": "Hoseni",
				"Knis Betesh Geniza List, Aleppo": "Hoseni",
				"ABRAHAM DWECK Pre1920": "Hoseni",
				"IDELSOHN Pre1923": "Hoseni",
				"S SAGIR Laniado": "Bayat",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "",
				"ASHEAR list": "Hoseni",
				"ASHEAR NOTES 1936-1940": "Bayat",
				"ABRAHAM E SHREM ~1945": "Bayat",
				"Argentina 1947 & Ezra Mishanieh": "Hoseni",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Hoseni",
				"GABRIEL A SHREM 1964 SUHV": "Hoseni",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Hoseni",
				"YOSEF YEHEZKEL Jerusalem 1975": "",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Hoseni",
				"Shaare Zimra YANANI Buenos Aires, 01": "Bayat",
				"BOZO, Ades, Shir Ushbaha 2005": "Hoseni",
				"Yishaq Yeranen Halabi": "Hoseni",
				"MOSHE AMASH (Shami)": "Ajam",
				"EZRA MASLATON TARAB (Shami)": "Mahour",
				"ABRAHAM SHAMRICHA (Shami)": "",
				"Victor Afya, Istanbul List": "",
				"Izak Alaluf, Izmir List": "",
				"Hallel VeZimrah, Greece List, 1926": "Bustanigar"
			},
			[Parsha.PEKUDEI]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Nawah",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Nawah",
				"TEBELE Pre1888": "Nawah",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Nawah",
				"YAAQOB ABADI-PARSIYA": "Nawah",
				"YISHAQ YEQAR ARGENTINA": "Nawah",
				"ADES: 24793": "Nawah",
				"Dibre Shelomo S KASSIN Pre1915": "Nawah",
				"Knis Betesh Geniza List, Aleppo": "Nawah",
				"ABRAHAM DWECK Pre1920": "Nawah",
				"IDELSOHN Pre1923": "Nawah",
				"S SAGIR Laniado": "Nawah",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Rast Saba",
				"ASHEAR list": "Nawah",
				"ASHEAR NOTES 1936-1940": "Nawah",
				"ABRAHAM E SHREM ~1945": "Saba",
				"Argentina 1947 & Ezra Mishanieh": "Nahwand",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Nawah",
				"GABRIEL A SHREM 1964 SUHV": "Nawah",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Bayat",
				"YOSEF YEHEZKEL Jerusalem 1975": "",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Nawah",
				"Shaare Zimra YANANI Buenos Aires, 01": "Nawah",
				"BOZO, Ades, Shir Ushbaha 2005": "Nawah",
				"Yishaq Yeranen Halabi": "Nawah",
				"MOSHE AMASH (Shami)": "Bayat",
				"EZRA MASLATON TARAB (Shami)": "Bayat",
				"ABRAHAM SHAMRICHA (Shami)": "Bayat",
				"Victor Afya, Istanbul List": "",
				"Izak Alaluf, Izmir List": "",
				"Hallel VeZimrah, Greece List, 1926": "Huzam"
			},
			[Parsha.VAYIKRA]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Rast",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Rast",
				"TEBELE Pre1888": "Rast",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Rast",
				"YAAQOB ABADI-PARSIYA": "Rast",
				"YISHAQ YEQAR ARGENTINA": "Rast",
				"ADES: 24793": "Rast",
				"Dibre Shelomo S KASSIN Pre1915": "Rast",
				"Knis Betesh Geniza List, Aleppo": "Rast",
				"ABRAHAM DWECK Pre1920": "Rast",
				"IDELSOHN Pre1923": "Rast",
				"S SAGIR Laniado": "Rast",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "",
				"ASHEAR list": "Rast",
				"ASHEAR NOTES 1936-1940": "Rast",
				"ABRAHAM E SHREM ~1945": "",
				"Argentina 1947 & Ezra Mishanieh": "Rast",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Rast",
				"GABRIEL A SHREM 1964 SUHV": "Rast",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Rast",
				"YOSEF YEHEZKEL Jerusalem 1975": "Rast",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Rast",
				"Shaare Zimra YANANI Buenos Aires, 01": "Rast",
				"BOZO, Ades, Shir Ushbaha 2005": "Rast",
				"Yishaq Yeranen Halabi": "Rast",
				"MOSHE AMASH (Shami)": "Rast",
				"EZRA MASLATON TARAB (Shami)": "Rast",
				"ABRAHAM SHAMRICHA (Shami)": "Rast",
				"Victor Afya, Istanbul List": "Sebah",
				"Izak Alaluf, Izmir List": "Hicaz",
				"Hallel VeZimrah, Greece List, 1926": "Saba"
			},
			[Parsha.TZAV]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Iraq",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Iraq",
				"TEBELE Pre1888": "Iraq",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Rahaw; Iraq",
				"YAAQOB ABADI-PARSIYA": "Rahaw/ Iraq",
				"YISHAQ YEQAR ARGENTINA": "Rahawi",
				"ADES: 24793": "Iraq",
				"Dibre Shelomo S KASSIN Pre1915": "Iraq",
				"Knis Betesh Geniza List, Aleppo": "Rahaw",
				"ABRAHAM DWECK Pre1920": "Rahaw",
				"IDELSOHN Pre1923": "Iraq",
				"S SAGIR Laniado": "Nawah",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Rahaw",
				"ASHEAR list": "Rahaw",
				"ASHEAR NOTES 1936-1940": "Bayat",
				"ABRAHAM E SHREM ~1945": "",
				"Argentina 1947 & Ezra Mishanieh": "Rahaw",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Iraq",
				"GABRIEL A SHREM 1964 SUHV": "Rahawi Nawah",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Bayat",
				"YOSEF YEHEZKEL Jerusalem 1975": "Iraq",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Nahwand",
				"Shaare Zimra YANANI Buenos Aires, 01": "Sigah",
				"BOZO, Ades, Shir Ushbaha 2005": "Nawah",
				"Yishaq Yeranen Halabi": "Nawah",
				"MOSHE AMASH (Shami)": "Nawah",
				"EZRA MASLATON TARAB (Shami)": "Bayat",
				"ABRAHAM SHAMRICHA (Shami)": "Bayat",
				"Victor Afya, Istanbul List": "Isfahan/ Acem Ashiran",
				"Izak Alaluf, Izmir List": "Segah",
				"Hallel VeZimrah, Greece List, 1926": "Hoseni?"
			},
			[Parsha.SHMINI]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Hoseni",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Hoseni",
				"TEBELE Pre1888": "",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Hoseni",
				"YAAQOB ABADI-PARSIYA": "Hoseni",
				"YISHAQ YEQAR ARGENTINA": "Hoseni",
				"ADES: 24793": "Hoseni",
				"Dibre Shelomo S KASSIN Pre1915": "Hoseni",
				"Knis Betesh Geniza List, Aleppo": "Hoseni",
				"ABRAHAM DWECK Pre1920": "Hoseni",
				"IDELSOHN Pre1923": "Hoseni",
				"S SAGIR Laniado": "Hoseni",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "",
				"ASHEAR list": "Hoseni",
				"ASHEAR NOTES 1936-1940": "Nahwand",
				"ABRAHAM E SHREM ~1945": "",
				"Argentina 1947 & Ezra Mishanieh": "Hoseni",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Hoseni",
				"GABRIEL A SHREM 1964 SUHV": "Hoseni",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Rast",
				"YOSEF YEHEZKEL Jerusalem 1975": "Hoseni",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Hoseni",
				"Shaare Zimra YANANI Buenos Aires, 01": "Bayat",
				"BOZO, Ades, Shir Ushbaha 2005": "Hoseni",
				"Yishaq Yeranen Halabi": "Hoseni",
				"MOSHE AMASH (Shami)": "Saba",
				"EZRA MASLATON TARAB (Shami)": "Saba",
				"ABRAHAM SHAMRICHA (Shami)": "Saba",
				"Victor Afya, Istanbul List": "Hicaz",
				"Izak Alaluf, Izmir List": "Hicaz",
				"Hallel VeZimrah, Greece List, 1926": "Bayati"
			},
			[Parsha.TAZRIA]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Bayat",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Bayat",
				"TEBELE Pre1888": "Bayat",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Bayat",
				"YAAQOB ABADI-PARSIYA": "Bayat",
				"YISHAQ YEQAR ARGENTINA": "Mehayar",
				"ADES: 24793": "Bayat",
				"Dibre Shelomo S KASSIN Pre1915": "Bayat",
				"Knis Betesh Geniza List, Aleppo": "Bayat",
				"ABRAHAM DWECK Pre1920": "Bayat",
				"IDELSOHN Pre1923": "Bayat",
				"S SAGIR Laniado": "Sigah",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Bayat",
				"ASHEAR list": "Sigah",
				"ASHEAR NOTES 1936-1940": "Bayat, Sigah",
				"ABRAHAM E SHREM ~1945": "",
				"Argentina 1947 & Ezra Mishanieh": "Sigah",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Bayat/ Rast",
				"GABRIEL A SHREM 1964 SUHV": "Saba / Bayat",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Bayat",
				"YOSEF YEHEZKEL Jerusalem 1975": "Mehayar",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Sigah",
				"Shaare Zimra YANANI Buenos Aires, 01": "Saba",
				"BOZO, Ades, Shir Ushbaha 2005": "Saba/ Bayat",
				"Yishaq Yeranen Halabi": "Saba",
				"MOSHE AMASH (Shami)": "Bayat",
				"EZRA MASLATON TARAB (Shami)": "Sigah",
				"ABRAHAM SHAMRICHA (Shami)": "Bayat",
				"Victor Afya, Istanbul List": "Mahur",
				"Izak Alaluf, Izmir List": "Acem Ashiran",
				"Hallel VeZimrah, Greece List, 1926": "Suzniq"
			},
			[Parsha.METZORA]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Iraq",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Iraq",
				"TEBELE Pre1888": "Iraq",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Rahaw",
				"YAAQOB ABADI-PARSIYA": "Nawah",
				"YISHAQ YEQAR ARGENTINA": "Sigah",
				"ADES: 24793": "Iraq",
				"Dibre Shelomo S KASSIN Pre1915": "Iraq",
				"Knis Betesh Geniza List, Aleppo": "Rahaw",
				"ABRAHAM DWECK Pre1920": "Nahwand",
				"IDELSOHN Pre1923": "Iraq",
				"S SAGIR Laniado": "Nawah",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "",
				"ASHEAR list": "",
				"ASHEAR NOTES 1936-1940": "Nahwand, Sigah",
				"ABRAHAM E SHREM ~1945": "",
				"Argentina 1947 & Ezra Mishanieh": "Sigah",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Saba or Sigah",
				"GABRIEL A SHREM 1964 SUHV": "Nahwand or Sigah",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Sigah",
				"YOSEF YEHEZKEL Jerusalem 1975": "",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Rast",
				"Shaare Zimra YANANI Buenos Aires, 01": "Nawah",
				"BOZO, Ades, Shir Ushbaha 2005": "Sigah/ Saba",
				"Yishaq Yeranen Halabi": "Saba",
				"MOSHE AMASH (Shami)": "Rast",
				"EZRA MASLATON TARAB (Shami)": "Bayat",
				"ABRAHAM SHAMRICHA (Shami)": "",
				"Victor Afya, Istanbul List": "",
				"Izak Alaluf, Izmir List": "Segah",
				"Hallel VeZimrah, Greece List, 1926": "Sigah?"
			},
			[Parsha.ACHREI_MOS]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Hijaz",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Hijaz",
				"TEBELE Pre1888": "Hijaz",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "(Hijaz)",
				"YAAQOB ABADI-PARSIYA": "Hijaz",
				"YISHAQ YEQAR ARGENTINA": "Hijaz",
				"ADES: 24793": "Hijaz",
				"Dibre Shelomo S KASSIN Pre1915": "Hijaz",
				"Knis Betesh Geniza List, Aleppo": "Hijaz",
				"ABRAHAM DWECK Pre1920": "Hijaz",
				"IDELSOHN Pre1923": "Hijaz",
				"S SAGIR Laniado": "Hijaz",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Hijaz",
				"ASHEAR list": "Hijaz",
				"ASHEAR NOTES 1936-1940": "Hijaz",
				"ABRAHAM E SHREM ~1945": "Hijaz",
				"Argentina 1947 & Ezra Mishanieh": "Hijaz",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Hijaz",
				"GABRIEL A SHREM 1964 SUHV": "Hijaz",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Nahwand",
				"YOSEF YEHEZKEL Jerusalem 1975": "Hijaz",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Hijaz",
				"Shaare Zimra YANANI Buenos Aires, 01": "Nahwand",
				"BOZO, Ades, Shir Ushbaha 2005": "Hijaz",
				"Yishaq Yeranen Halabi": "Hijaz",
				"MOSHE AMASH (Shami)": "Saba",
				"EZRA MASLATON TARAB (Shami)": "Saba",
				"ABRAHAM SHAMRICHA (Shami)": "Bayat",
				"Hallel VeZimrah, Greece List, 1926": "Nahoft"
			},
			[Parsha.KEDOSHIM]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Saba",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Saba",
				"YAAQOB ABADI-PARSIYA": "Iraq/ Saba",
				"YISHAQ YEQAR ARGENTINA": "Iraq",
				"ADES: 24793": "Saba",
				"Dibre Shelomo S KASSIN Pre1915": "Saba",
				"Knis Betesh Geniza List, Aleppo": "Saba",
				"ABRAHAM DWECK Pre1920": "Saba",
				"IDELSOHN Pre1923": "Saba",
				"S SAGIR Laniado": "Saba",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Rast",
				"ASHEAR list": "Iraq",
				"ASHEAR NOTES 1936-1940": "Saba",
				"Argentina 1947 & Ezra Mishanieh": "Iraq",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Saba",
				"GABRIEL A SHREM 1964 SUHV": "Saba",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Rast",
				"YOSEF YEHEZKEL Jerusalem 1975": "Saba",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Saba",
				"Shaare Zimra YANANI Buenos Aires, 01": "Bayat",
				"BOZO, Ades, Shir Ushbaha 2005": "Saba",
				"Yishaq Yeranen Halabi": "Saba",
				"MOSHE AMASH (Shami)": "Ajam",
				"EZRA MASLATON TARAB (Shami)": "Sigah",
				"ABRAHAM SHAMRICHA (Shami)": "Sigah",
				"Hallel VeZimrah, Greece List, 1926": "Hijaz"
			},
			[Parsha.EMOR]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Ashiran",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Ashiran",
				"TEBELE Pre1888": "Ashiran",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Ashiran; Saba",
				"YAAQOB ABADI-PARSIYA": "Ashiran",
				"YISHAQ YEQAR ARGENTINA": "Ashiran",
				"ADES: 24793": "Ashiran",
				"Dibre Shelomo S KASSIN Pre1915": "Ashiran",
				"Knis Betesh Geniza List, Aleppo": "Ashiran",
				"ABRAHAM DWECK Pre1920": "Sigah",
				"IDELSOHN Pre1923": "Ashiran",
				"S SAGIR Laniado": "Ashiran",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "",
				"ASHEAR list": "Ashiran",
				"ASHEAR NOTES 1936-1940": "Sigah/ Hoseni",
				"ABRAHAM E SHREM ~1945": "",
				"Argentina 1947 & Ezra Mishanieh": "Ashiran",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Hoseni or Sigah",
				"GABRIEL A SHREM 1964 SUHV": "Sigah / Hoseni",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Sigah",
				"YOSEF YEHEZKEL Jerusalem 1975": "Oj",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Hoseni",
				"Shaare Zimra YANANI Buenos Aires, 01": "Sigah",
				"BOZO, Ades, Shir Ushbaha 2005": "Sigah or Hoseni",
				"Yishaq Yeranen Halabi": "Sigah",
				"MOSHE AMASH (Shami)": "Rast",
				"EZRA MASLATON TARAB (Shami)": "Rast",
				"ABRAHAM SHAMRICHA (Shami)": "Rast",
				"Victor Afya, Istanbul List": "",
				"Izak Alaluf, Izmir List": "",
				"Hallel VeZimrah, Greece List, 1926": "Busaliq"
			},
			[Parsha.BEHAR]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Nawah",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Nawah",
				"TEBELE Pre1888": "Nawah",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "",
				"YAAQOB ABADI-PARSIYA": "Nawah",
				"YISHAQ YEQAR ARGENTINA": "Saba",
				"ADES: 24793": "Nawah",
				"Dibre Shelomo S KASSIN Pre1915": "Nawah",
				"Knis Betesh Geniza List, Aleppo": "Nawah",
				"ABRAHAM DWECK Pre1920": "Nawah",
				"IDELSOHN Pre1923": "Nawah",
				"S SAGIR Laniado": "Nawah",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Saba",
				"ASHEAR list": "",
				"ASHEAR NOTES 1936-1940": "Nawah",
				"ABRAHAM E SHREM ~1945": "Saba",
				"Argentina 1947 & Ezra Mishanieh": "",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Nawah",
				"GABRIEL A SHREM 1964 SUHV": "Saba / Nawah",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Bayat",
				"YOSEF YEHEZKEL Jerusalem 1975": "Nahwand",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Nawah",
				"Shaare Zimra YANANI Buenos Aires, 01": "Nawah",
				"BOZO, Ades, Shir Ushbaha 2005": "Nawah or Saba",
				"Yishaq Yeranen Halabi": "Nawah",
				"MOSHE AMASH (Shami)": "Sigah",
				"EZRA MASLATON TARAB (Shami)": "",
				"ABRAHAM SHAMRICHA (Shami)": "Ajam",
				"Victor Afya, Istanbul List": "",
				"Izak Alaluf, Izmir List": "",
				"Hallel VeZimrah, Greece List, 1926": "Qargigar?"
			},
			[Parsha.BECHUKOSAI]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Nawah",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Nawah",
				"TEBELE Pre1888": "Nawah",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Nawah",
				"YAAQOB ABADI-PARSIYA": "Nawah",
				"YISHAQ YEQAR ARGENTINA": "Nawah",
				"ADES: 24793": "Nawah",
				"Dibre Shelomo S KASSIN Pre1915": "Rahaw",
				"Knis Betesh Geniza List, Aleppo": "Bayat",
				"ABRAHAM DWECK Pre1920": "",
				"IDELSOHN Pre1923": "Nawah/ Bayat",
				"S SAGIR Laniado": "Nahwand",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "",
				"ASHEAR list": "Nawah",
				"ASHEAR NOTES 1936-1940": "",
				"ABRAHAM E SHREM ~1945": "",
				"Argentina 1947 & Ezra Mishanieh": "Nahwand",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Bayat",
				"GABRIEL A SHREM 1964 SUHV": "Nahwand/ Nawah",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Nahwand",
				"YOSEF YEHEZKEL Jerusalem 1975": "Kurd",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Saba",
				"Shaare Zimra YANANI Buenos Aires, 01": "Rast",
				"BOZO, Ades, Shir Ushbaha 2005": "Nawah/ Bayat",
				"Yishaq Yeranen Halabi": "Bayat",
				"MOSHE AMASH (Shami)": "Bayat",
				"EZRA MASLATON TARAB (Shami)": "Ajam",
				"ABRAHAM SHAMRICHA (Shami)": "",
				"Victor Afya, Istanbul List": "",
				"Izak Alaluf, Izmir List": "",
				"Hallel VeZimrah, Greece List, 1926": "Iraq"
			},
			[Parsha.BAMIDBAR]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Mehayar",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Mehayar",
				"TEBELE Pre1888": "Mehayar",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Nawah",
				"YAAQOB ABADI-PARSIYA": "Rast",
				"YISHAQ YEQAR ARGENTINA": "Rast",
				"ADES: 24793": "Mehayar",
				"Dibre Shelomo S KASSIN Pre1915": "Mehayar/ Rast",
				"Knis Betesh Geniza List, Aleppo": "Rast",
				"ABRAHAM DWECK Pre1920": "",
				"IDELSOHN Pre1923": "Mehayar",
				"S SAGIR Laniado": "Rast",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Rast",
				"ASHEAR list": "Mehayar",
				"ASHEAR NOTES 1936-1940": "Hoseni/ Rast",
				"ABRAHAM E SHREM ~1945": "Rast",
				"Argentina 1947 & Ezra Mishanieh": "Mehayar",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Saba or Rast",
				"GABRIEL A SHREM 1964 SUHV": "Hoseni/ Rast",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Rast",
				"YOSEF YEHEZKEL Jerusalem 1975": "Rast",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Rast",
				"Shaare Zimra YANANI Buenos Aires, 01": "Bayat",
				"BOZO, Ades, Shir Ushbaha 2005": "Hoseni/ Rast",
				"Yishaq Yeranen Halabi": "Bayat",
				"MOSHE AMASH (Shami)": "Rast/Ajam",
				"EZRA MASLATON TARAB (Shami)": "Rast",
				"ABRAHAM SHAMRICHA (Shami)": "Rast",
				"Hallel VeZimrah, Greece List, 1926": "Haqqordo?"
			},
			[Parsha.NASSO]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Saba",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Saba",
				"TEBELE Pre1888": "Saba",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Saba",
				"YAAQOB ABADI-PARSIYA": "Saba",
				"YISHAQ YEQAR ARGENTINA": "Saba",
				"ADES: 24793": "Saba",
				"Dibre Shelomo S KASSIN Pre1915": "Saba",
				"Knis Betesh Geniza List, Aleppo": "Saba",
				"ABRAHAM DWECK Pre1920": "Saba",
				"IDELSOHN Pre1923": "Saba",
				"S SAGIR Laniado": "Saba",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "",
				"ASHEAR list": "Saba",
				"ASHEAR NOTES 1936-1940": "Saba",
				"ABRAHAM E SHREM ~1945": "Saba",
				"Argentina 1947 & Ezra Mishanieh": "Saba",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Hoseni/ Saba",
				"GABRIEL A SHREM 1964 SUHV": "Saba",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Saba",
				"YOSEF YEHEZKEL Jerusalem 1975": "Zangiran",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Hoseni",
				"Shaare Zimra YANANI Buenos Aires, 01": "Saba",
				"BOZO, Ades, Shir Ushbaha 2005": "Saba or Rast",
				"Yishaq Yeranen Halabi": "Hoseni/ Saba",
				"MOSHE AMASH (Shami)": "Sigah",
				"EZRA MASLATON TARAB (Shami)": "Bayat",
				"ABRAHAM SHAMRICHA (Shami)": "Bayat",
				"Hallel VeZimrah, Greece List, 1926": "Hijaz"
			},
			[Parsha.BEHAALOSCHA]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Hoseni",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Oj",
				"TEBELE Pre1888": "Sigah",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Sigah; Hoseni",
				"YAAQOB ABADI-PARSIYA": "Sigah",
				"YISHAQ YEQAR ARGENTINA": "Sigah",
				"ADES: 24793": "Oj",
				"Dibre Shelomo S KASSIN Pre1915": "Hoseni",
				"Knis Betesh Geniza List, Aleppo": "Sigah",
				"ABRAHAM DWECK Pre1920": "Sigah",
				"IDELSOHN Pre1923": "Sigah",
				"S SAGIR Laniado": "Sigah",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Sigah",
				"ASHEAR list": "Sigah",
				"ASHEAR NOTES 1936-1940": "Sigah",
				"ABRAHAM E SHREM ~1945": "Sigah",
				"Argentina 1947 & Ezra Mishanieh": "Sigah",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Sigah",
				"GABRIEL A SHREM 1964 SUHV": "Sigah",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Sigah",
				"YOSEF YEHEZKEL Jerusalem 1975": "Sigah",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Sigah",
				"Shaare Zimra YANANI Buenos Aires, 01": "Sigah",
				"BOZO, Ades, Shir Ushbaha 2005": "Sigah",
				"Yishaq Yeranen Halabi": "Sigah",
				"MOSHE AMASH (Shami)": "Nawah",
				"EZRA MASLATON TARAB (Shami)": "Rahawi",
				"ABRAHAM SHAMRICHA (Shami)": "Nawah",
				"Hallel VeZimrah, Greece List, 1926": "Ushaq"
			},
			[Parsha.SHLACH]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Iraq",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Iraq/ Nawah",
				"TEBELE Pre1888": "Iraq",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Iraq; Nawah",
				"YAAQOB ABADI-PARSIYA": "Nawah",
				"YISHAQ YEQAR ARGENTINA": "Hijaz",
				"ADES: 24793": "Iraq/ Nawah",
				"Dibre Shelomo S KASSIN Pre1915": "Iraq",
				"Knis Betesh Geniza List, Aleppo": "Iraq",
				"ABRAHAM DWECK Pre1920": "Hijaz",
				"IDELSOHN Pre1923": "Iraq",
				"S SAGIR Laniado": "Nawah",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Hijaz",
				"ASHEAR list": "Iraq",
				"ASHEAR NOTES 1936-1940": "Hijaz",
				"ABRAHAM E SHREM ~1945": "Hijaz",
				"Argentina 1947 & Ezra Mishanieh": "Iraq",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Iraq/ Nawah",
				"GABRIEL A SHREM 1964 SUHV": "Hijaz",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Nahwand",
				"YOSEF YEHEZKEL Jerusalem 1975": "Shuri",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Nawah",
				"Shaare Zimra YANANI Buenos Aires, 01": "Nahwand",
				"BOZO, Ades, Shir Ushbaha 2005": "Hijaz/ Nahwand",
				"Yishaq Yeranen Halabi": "Nahwand",
				"MOSHE AMASH (Shami)": "Saba",
				"EZRA MASLATON TARAB (Shami)": "Saba",
				"ABRAHAM SHAMRICHA (Shami)": "Saba",
				"Hallel VeZimrah, Greece List, 1926": "Huzam"
			},
			[Parsha.KORACH]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Hoseni combined",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Hoseni",
				"TEBELE Pre1888": "Hoseni",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Hoseni Bayat combined",
				"YAAQOB ABADI-PARSIYA": "Hoseni",
				"YISHAQ YEQAR ARGENTINA": "Hoseni",
				"ADES: 24793": "Hoseni",
				"Dibre Shelomo S KASSIN Pre1915": "Hoseni",
				"Knis Betesh Geniza List, Aleppo": "Hoseni combined",
				"ABRAHAM DWECK Pre1920": "Hoseni combined",
				"IDELSOHN Pre1923": "Hoseni",
				"S SAGIR Laniado": "Hoseni",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Hoseni",
				"ASHEAR list": "Hoseni",
				"ASHEAR NOTES 1936-1940": "Bayat",
				"ABRAHAM E SHREM ~1945": "Nahwand",
				"Argentina 1947 & Ezra Mishanieh": "Hoseni",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Hoseni",
				"GABRIEL A SHREM 1964 SUHV": "Nahwand",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Bayat",
				"YOSEF YEHEZKEL Jerusalem 1975": "Hoseni",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Nahwand",
				"Shaare Zimra YANANI Buenos Aires, 01": "Bayat",
				"BOZO, Ades, Shir Ushbaha 2005": "Nahwand/ Hoseni",
				"Yishaq Yeranen Halabi": "Hoseni",
				"MOSHE AMASH (Shami)": "Bayat",
				"EZRA MASLATON TARAB (Shami)": "Sigah",
				"ABRAHAM SHAMRICHA (Shami)": "Sigah",
				"Hallel VeZimrah, Greece List, 1926": "Iraq"
			},
			[Parsha.CHUKAS]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Hoseni combined",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Hoseni",
				"TEBELE Pre1888": "Hoseni",
				"YAAQOB ABADI-PARSIYA": "Bayat",
				"ADES: 24793": "Hoseni",
				"Dibre Shelomo S KASSIN Pre1915": "Rast",
				"IDELSOHN Pre1923": "Rast",
				"S SAGIR Laniado": "Mahour",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Ashiran",
				"ASHEAR NOTES 1936-1940": "Bayat",
				"ABRAHAM E SHREM ~1945": "Hoseni",
				"Argentina 1947 & Ezra Mishanieh": "Hoseni",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Rast",
				"GABRIEL A SHREM 1964 SUHV": "Hoseni",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Ajam",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Rast",
				"BOZO, Ades, Shir Ushbaha 2005": "Rast / Hoseni",
				"Yishaq Yeranen Halabi": "Rast",
				"MOSHE AMASH (Shami)": "Ajam",
				"EZRA MASLATON TARAB (Shami)": "Bayat",
				"ABRAHAM SHAMRICHA (Shami)": "Ajam",
				"Hallel VeZimrah, Greece List, 1926": "Suzniq"
			},
			[Parsha.BALAK]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Bayat",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Bayat",
				"TEBELE Pre1888": "Bayat",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Bayat",
				"YAAQOB ABADI-PARSIYA": "?",
				"YISHAQ YEQAR ARGENTINA": "Rast",
				"ADES: 24793": "Bayat",
				"Dibre Shelomo S KASSIN Pre1915": "Bayat",
				"Knis Betesh Geniza List, Aleppo": "Bayat",
				"ABRAHAM DWECK Pre1920": "Bayat",
				"IDELSOHN Pre1923": "Bayat",
				"S SAGIR Laniado": "Bayat",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Rast",
				"ASHEAR list": "Nahwand",
				"ASHEAR NOTES 1936-1940": "Nahwand",
				"ABRAHAM E SHREM ~1945": "Mahour",
				"Argentina 1947 & Ezra Mishanieh": "Nahwand",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Bayat",
				"GABRIEL A SHREM 1964 SUHV": "Mahour",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Bayat",
				"YOSEF YEHEZKEL Jerusalem 1975": "",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Bayat",
				"Shaare Zimra YANANI Buenos Aires, 01": "Rast",
				"BOZO, Ades, Shir Ushbaha 2005": "Bayat/ Mahour",
				"Yishaq Yeranen Halabi": "Bayat",
				"MOSHE AMASH (Shami)": "Sigah",
				"EZRA MASLATON TARAB (Shami)": "Bayat",
				"ABRAHAM SHAMRICHA (Shami)": "Bayat",
				"Hallel VeZimrah, Greece List, 1926": "Sigah"
			},
			[Parsha.PINCHAS]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Bayat",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Saba",
				"TEBELE Pre1888": "Saba",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Saba",
				"YAAQOB ABADI-PARSIYA": "Saba",
				"YISHAQ YEQAR ARGENTINA": "Saba",
				"ADES: 24793": "Saba",
				"Dibre Shelomo S KASSIN Pre1915": "Saba",
				"Knis Betesh Geniza List, Aleppo": "Saba",
				"ABRAHAM DWECK Pre1920": "Saba",
				"IDELSOHN Pre1923": "Saba",
				"S SAGIR Laniado": "Saba",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Saba",
				"ASHEAR list": "Saba",
				"ASHEAR NOTES 1936-1940": "Saba or Bayat",
				"ABRAHAM E SHREM ~1945": "Saba",
				"Argentina 1947 & Ezra Mishanieh": "Saba",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Saba",
				"GABRIEL A SHREM 1964 SUHV": "Saba",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Saba",
				"YOSEF YEHEZKEL Jerusalem 1975": "Bustanigar",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Saba",
				"Shaare Zimra YANANI Buenos Aires, 01": "Saba",
				"BOZO, Ades, Shir Ushbaha 2005": "Saba",
				"Yishaq Yeranen Halabi": "Saba",
				"MOSHE AMASH (Shami)": "Saba",
				"EZRA MASLATON TARAB (Shami)": "Saba",
				"ABRAHAM SHAMRICHA (Shami)": "Saba",
				"Hallel VeZimrah, Greece List, 1926": "Muhayer"
			},
			[Parsha.MATOS]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Nawah",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Nawah",
				"TEBELE Pre1888": "Nawah",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Nawah",
				"YAAQOB ABADI-PARSIYA": "Nawah",
				"YISHAQ YEQAR ARGENTINA": "Bayat",
				"ADES: 24793": "Nawah",
				"Dibre Shelomo S KASSIN Pre1915": "Nawah",
				"Knis Betesh Geniza List, Aleppo": "Nawah",
				"ABRAHAM DWECK Pre1920": "Nawah",
				"IDELSOHN Pre1923": "Nawah",
				"S SAGIR Laniado": "Nawah-Nahwand",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Rahaw",
				"ASHEAR list": "Nawah",
				"ASHEAR NOTES 1936-1940": "Bayat",
				"ABRAHAM E SHREM ~1945": "Nahwand",
				"Argentina 1947 & Ezra Mishanieh": "Nahwand",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Nawah",
				"GABRIEL A SHREM 1964 SUHV": "Nawah/ Nahwand",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Saba",
				"YOSEF YEHEZKEL Jerusalem 1975": "Nahwand",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Saba",
				"Shaare Zimra YANANI Buenos Aires, 01": "Nawah",
				"BOZO, Ades, Shir Ushbaha 2005": "Nawah-Nahwand",
				"Yishaq Yeranen Halabi": "Nawah",
				"MOSHE AMASH (Shami)": "Rast",
				"EZRA MASLATON TARAB (Shami)": "Mahour",
				"ABRAHAM SHAMRICHA (Shami)": "Bayat",
				"Hallel VeZimrah, Greece List, 1926": "Saba"
			},
			[Parsha.MASEI]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Saba",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Saba",
				"TEBELE Pre1888": "Saba",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Saba",
				"YAAQOB ABADI-PARSIYA": "Nahwand",
				"YISHAQ YEQAR ARGENTINA": "Nahwand",
				"ADES: 24793": "Saba",
				"Dibre Shelomo S KASSIN Pre1915": "Mehayar",
				"Knis Betesh Geniza List, Aleppo": "Saba",
				"IDELSOHN Pre1923": "Saba",
				"S SAGIR Laniado": "Nawah / Nahwand",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Saba",
				"ASHEAR list": "Saba",
				"ASHEAR NOTES 1936-1940": "Nawah",
				"ABRAHAM E SHREM ~1945": "Saba",
				"Argentina 1947 & Ezra Mishanieh": "Saba",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Saba",
				"GABRIEL A SHREM 1964 SUHV": "Saba",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Nahwand",
				"YOSEF YEHEZKEL Jerusalem 1975": "Saba - Isfahan",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Nahwand",
				"Shaare Zimra YANANI Buenos Aires, 01": "Nahwand",
				"BOZO, Ades, Shir Ushbaha 2005": "Saba / Bayat",
				"Yishaq Yeranen Halabi": "Saba",
				"MOSHE AMASH (Shami)": "Bayat",
				"EZRA MASLATON TARAB (Shami)": "Bayat",
				"ABRAHAM SHAMRICHA (Shami)": "Bayat",
				"Hallel VeZimrah, Greece List, 1926": "Nahawand"
			},
			[Parsha.DEVARIM]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Hijaz",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Hijaz",
				"TEBELE Pre1888": "Hijaz",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Hijaz",
				"YAAQOB ABADI-PARSIYA": "Hijaz",
				"YISHAQ YEQAR ARGENTINA": "Hijaz",
				"ADES: 24793": "Hijaz",
				"Dibre Shelomo S KASSIN Pre1915": "Hijaz",
				"Knis Betesh Geniza List, Aleppo": "Hijaz",
				"ABRAHAM DWECK Pre1920": "Hijaz",
				"IDELSOHN Pre1923": "Hijaz",
				"S SAGIR Laniado": "Hijaz",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Hijaz",
				"ASHEAR list": "Hijaz",
				"ASHEAR NOTES 1936-1940": "Hijaz",
				"ABRAHAM E SHREM ~1945": "Hijaz",
				"Argentina 1947 & Ezra Mishanieh": "Hijaz",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Hijaz",
				"GABRIEL A SHREM 1964 SUHV": "Hijaz",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Hijaz",
				"YOSEF YEHEZKEL Jerusalem 1975": "Zangiran",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Hijaz",
				"Shaare Zimra YANANI Buenos Aires, 01": "Hijaz",
				"BOZO, Ades, Shir Ushbaha 2005": "Hijaz",
				"Yishaq Yeranen Halabi": "Hijaz",
				"MOSHE AMASH (Shami)": "Hijaz",
				"EZRA MASLATON TARAB (Shami)": "Hijaz",
				"ABRAHAM SHAMRICHA (Shami)": "Hijaz",
				"Hallel VeZimrah, Greece List, 1926": "Ajam"
			},
			[Parsha.VAESCHANAN]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Hoseni",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Hoseni",
				"TEBELE Pre1888": "Hoseni",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Hoseni; Ashiran",
				"YAAQOB ABADI-PARSIYA": "Hoseni",
				"YISHAQ YEQAR ARGENTINA": "Hoseni",
				"ADES: 24793": "Hoseni",
				"Dibre Shelomo S KASSIN Pre1915": "Hoseni",
				"Knis Betesh Geniza List, Aleppo": "Ashiran",
				"ABRAHAM DWECK Pre1920": "Ashiran",
				"IDELSOHN Pre1923": "Hoseni",
				"S SAGIR Laniado": "Hoseni",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Hoseni",
				"ASHEAR list": "Hoseni",
				"ASHEAR NOTES 1936-1940": "Hoseni",
				"ABRAHAM E SHREM ~1945": "Hoseni",
				"Argentina 1947 & Ezra Mishanieh": "Hoseni",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Hoseni",
				"GABRIEL A SHREM 1964 SUHV": "Hoseni",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Bayat",
				"YOSEF YEHEZKEL Jerusalem 1975": "Hoseni",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Hoseni",
				"Shaare Zimra YANANI Buenos Aires, 01": "Bayat",
				"BOZO, Ades, Shir Ushbaha 2005": "Hoseni",
				"Yishaq Yeranen Halabi": "Hoseni",
				"MOSHE AMASH (Shami)": "Rast",
				"EZRA MASLATON TARAB (Shami)": "Rast",
				"ABRAHAM SHAMRICHA (Shami)": "Rast",
				"Hallel VeZimrah, Greece List, 1926": "Rast"
			},
			[Parsha.EIKEV]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "(MISSING)",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Sigah",
				"TEBELE Pre1888": "Sigah",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Sigah",
				"YAAQOB ABADI-PARSIYA": "Sigah",
				"YISHAQ YEQAR ARGENTINA": "Rast",
				"ADES: 24793": "Sigah",
				"Dibre Shelomo S KASSIN Pre1915": "Sigah",
				"Knis Betesh Geniza List, Aleppo": "Sigah",
				"ABRAHAM DWECK Pre1920": "Sigah",
				"IDELSOHN Pre1923": "Sigah",
				"S SAGIR Laniado": "Sigah",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Rast",
				"ASHEAR list": "Sigah",
				"ASHEAR NOTES 1936-1940": "Sigah-Iraq",
				"ABRAHAM E SHREM ~1945": "Sigah",
				"Argentina 1947 & Ezra Mishanieh": "Sigah",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Sigah",
				"GABRIEL A SHREM 1964 SUHV": "Sigah",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Sigah",
				"YOSEF YEHEZKEL Jerusalem 1975": "Sigah",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Sigah",
				"Shaare Zimra YANANI Buenos Aires, 01": "Rast",
				"BOZO, Ades, Shir Ushbaha 2005": "Sigah-Iraq",
				"Yishaq Yeranen Halabi": "Sigah",
				"MOSHE AMASH (Shami)": "Sigah",
				"EZRA MASLATON TARAB (Shami)": "Sigah",
				"ABRAHAM SHAMRICHA (Shami)": "Sigah",
				"Hallel VeZimrah, Greece List, 1926": "Qargigar"
			},
			[Parsha.REEH]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Iraq",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Iraq/ Rast",
				"TEBELE Pre1888": "Ashiran",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Iraq",
				"YAAQOB ABADI-PARSIYA": "Rast",
				"YISHAQ YEQAR ARGENTINA": "Ashiran",
				"ADES: 24793": "Iraq",
				"Dibre Shelomo S KASSIN Pre1915": "Iraq",
				"Knis Betesh Geniza List, Aleppo": "Saba",
				"ABRAHAM DWECK Pre1920": "Saba",
				"IDELSOHN Pre1923": "Iraq",
				"S SAGIR Laniado": "Nahwand",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Nawah",
				"ASHEAR list": "Ashiran",
				"ASHEAR NOTES 1936-1940": "Bayat",
				"ABRAHAM E SHREM ~1945": "Bayat",
				"Argentina 1947 & Ezra Mishanieh": "Ashiran",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Sigah/ Rast",
				"GABRIEL A SHREM 1964 SUHV": "Rast",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Rast",
				"YOSEF YEHEZKEL Jerusalem 1975": "Rast",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Rast",
				"Shaare Zimra YANANI Buenos Aires, 01": "Bayat",
				"BOZO, Ades, Shir Ushbaha 2005": "Rast",
				"Yishaq Yeranen Halabi": "Rast",
				"MOSHE AMASH (Shami)": "Bayat",
				"EZRA MASLATON TARAB (Shami)": "Nawah",
				"ABRAHAM SHAMRICHA (Shami)": "Nawah",
				"Hallel VeZimrah, Greece List, 1926": "Hoseni?"
			},
			[Parsha.SHOFTIM]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Saba",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Saba/ Sigah",
				"TEBELE Pre1888": "Saba",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Sigah; Saba",
				"YAAQOB ABADI-PARSIYA": "Saba",
				"YISHAQ YEQAR ARGENTINA": "Ajam",
				"ADES: 24793": "Saba/ Sigah",
				"Dibre Shelomo S KASSIN Pre1915": "Sasgar",
				"Knis Betesh Geniza List, Aleppo": "Ajam",
				"ABRAHAM DWECK Pre1920": "Ajam",
				"IDELSOHN Pre1923": "Sigah",
				"S SAGIR Laniado": "Ajam",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Ajam",
				"ASHEAR list": "Saba",
				"ASHEAR NOTES 1936-1940": "Ajam",
				"ABRAHAM E SHREM ~1945": "Ajam",
				"Argentina 1947 & Ezra Mishanieh": "Saba",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Saba",
				"GABRIEL A SHREM 1964 SUHV": "Ajam",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Ajam",
				"YOSEF YEHEZKEL Jerusalem 1975": "Girka",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Saba or Ajam",
				"Shaare Zimra YANANI Buenos Aires, 01": "Ajam",
				"BOZO, Ades, Shir Ushbaha 2005": "Ajam / Sigah",
				"Yishaq Yeranen Halabi": "Ajam",
				"MOSHE AMASH (Shami)": "Ajam",
				"EZRA MASLATON TARAB (Shami)": "Ajam",
				"ABRAHAM SHAMRICHA (Shami)": "Ajam",
				"Hallel VeZimrah, Greece List, 1926": "Hijaz"
			},
			[Parsha.KI_SEITZEI]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Saba",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Saba/ Rast",
				"TEBELE Pre1888": "Saba",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Rast; Iraq; Nawah",
				"YAAQOB ABADI-PARSIYA": "Rast",
				"YISHAQ YEQAR ARGENTINA": "Saba",
				"ADES: 24793": "Saba/ Rast",
				"Dibre Shelomo S KASSIN Pre1915": "Saba",
				"Knis Betesh Geniza List, Aleppo": "Rast",
				"ABRAHAM DWECK Pre1920": "Nahwand",
				"IDELSOHN Pre1923": "Saba",
				"S SAGIR Laniado": "Rast",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Saba",
				"ASHEAR list": "Nawah",
				"ASHEAR NOTES 1936-1940": "Saba / Sigah",
				"ABRAHAM E SHREM ~1945": "Saba",
				"Argentina 1947 & Ezra Mishanieh": "Nahwand",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Rast",
				"GABRIEL A SHREM 1964 SUHV": "Saba",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Saba",
				"YOSEF YEHEZKEL Jerusalem 1975": "Bayat / Ajam",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Rast",
				"Shaare Zimra YANANI Buenos Aires, 01": "Saba",
				"BOZO, Ades, Shir Ushbaha 2005": "Saba",
				"Yishaq Yeranen Halabi": "Saba",
				"MOSHE AMASH (Shami)": "Sigah",
				"EZRA MASLATON TARAB (Shami)": "Sigah",
				"ABRAHAM SHAMRICHA (Shami)": "Sigah",
				"Hallel VeZimrah, Greece List, 1926": "Bayati"
			},
			[Parsha.KI_SAVO]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Iraq",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Iraq",
				"TEBELE Pre1888": "Iraq",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Iraq",
				"YAAQOB ABADI-PARSIYA": "Iraq",
				"YISHAQ YEQAR ARGENTINA": "Nawah",
				"ADES: 24793": "Iraq",
				"Dibre Shelomo S KASSIN Pre1915": "Iraq",
				"Knis Betesh Geniza List, Aleppo": "Iraq",
				"ABRAHAM DWECK Pre1920": "Rast",
				"IDELSOHN Pre1923": "Iraq",
				"S SAGIR Laniado": "Sigah",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "-",
				"ASHEAR list": "Iraq",
				"ASHEAR NOTES 1936-1940": "Nawah/ Saba/ Sigah",
				"ABRAHAM E SHREM ~1945": "Sigah",
				"Argentina 1947 & Ezra Mishanieh": "Iraq",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Sigah",
				"GABRIEL A SHREM 1964 SUHV": "Sigah",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Sigah",
				"YOSEF YEHEZKEL Jerusalem 1975": "Oj",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Hijaz",
				"Shaare Zimra YANANI Buenos Aires, 01": "Sigah",
				"BOZO, Ades, Shir Ushbaha 2005": "Sigah-Iraq",
				"Yishaq Yeranen Halabi": "Sigah",
				"MOSHE AMASH (Shami)": "Saba",
				"EZRA MASLATON TARAB (Shami)": "Saba",
				"ABRAHAM SHAMRICHA (Shami)": "Bayat",
				"Hallel VeZimrah, Greece List, 1926": "Sigah?"
			},
			[Parsha.NITZAVIM]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Nawah",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Nawah",
				"TEBELE Pre1888": "Nawah",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Nawah",
				"YAAQOB ABADI-PARSIYA": "Nawah",
				"YISHAQ YEQAR ARGENTINA": "Rast",
				"ADES: 24793": "Nawah",
				"Dibre Shelomo S KASSIN Pre1915": "Nawah",
				"Knis Betesh Geniza List, Aleppo": "Nawah",
				"ABRAHAM DWECK Pre1920": "Hijaz",
				"IDELSOHN Pre1923": "Nawah",
				"S SAGIR Laniado": "Nawah",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Rast",
				"ASHEAR list": "Nawah",
				"ASHEAR NOTES 1936-1940": "Hijaz, H/H",
				"ABRAHAM E SHREM ~1945": "Nahwand",
				"Argentina 1947 & Ezra Mishanieh": "Nahwand",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Nawah",
				"GABRIEL A SHREM 1964 SUHV": "Nawa/ Nahwand",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Rast",
				"YOSEF YEHEZKEL Jerusalem 1975": "Rast",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Nahwand",
				"Shaare Zimra YANANI Buenos Aires, 01": "Bayat",
				"BOZO, Ades, Shir Ushbaha 2005": "Nawah-Nahwand",
				"Yishaq Yeranen Halabi": "Nawah",
				"MOSHE AMASH (Shami)": "Ajam",
				"EZRA MASLATON TARAB (Shami)": "Bayat",
				"ABRAHAM SHAMRICHA (Shami)": "Sigah",
				"Hallel VeZimrah, Greece List, 1926": "Saba"
			},
			[Parsha.VAYEILECH]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Nawah",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Nawah",
				"TEBELE Pre1888": "",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "",
				"YAAQOB ABADI-PARSIYA": "Rast",
				"YISHAQ YEQAR ARGENTINA": "Hijaz",
				"ADES: 24793": "Nawah",
				"Dibre Shelomo S KASSIN Pre1915": "Nawah",
				"Knis Betesh Geniza List, Aleppo": "",
				"ABRAHAM DWECK Pre1920": "",
				"IDELSOHN Pre1923": "",
				"S SAGIR Laniado": "Nawah",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "Hoseni",
				"ASHEAR list": "",
				"ASHEAR NOTES 1936-1940": "Hoseni",
				"ABRAHAM E SHREM ~1945": "Bayat/ Hoseni",
				"Argentina 1947 & Ezra Mishanieh": "Ajam",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Rast",
				"GABRIEL A SHREM 1964 SUHV": "Hoseni",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Bayat",
				"YOSEF YEHEZKEL Jerusalem 1975": "",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Rast",
				"Shaare Zimra YANANI Buenos Aires, 01": "Bayat",
				"BOZO, Ades, Shir Ushbaha 2005": "Rast/ Hoseni",
				"Yishaq Yeranen Halabi": "Rast",
				"MOSHE AMASH (Shami)": "Bayat",
				"EZRA MASLATON TARAB (Shami)": "",
				"ABRAHAM SHAMRICHA (Shami)": "Ajam",
				"Hallel VeZimrah, Greece List, 1926": "Hoseni"
			},
			[Parsha.HAAZINU]: {
				"TABBUSH Ms NLI 8*7622, Aleppo": "Hoseni",
				"R COHEN \"SHIR USHBAHA\" Jerusalem, 1905": "Hoseni",
				"TEBELE Pre1888": "Hoseni",
				"ELIE SHAUL COHEN FROM AINTAB, ~1880": "Hoseni",
				"YAAQOB ABADI-PARSIYA": "Hoseni",
				"YISHAQ YEQAR ARGENTINA": "Hoseni",
				"ADES: 24793": "Hoseni",
				"Dibre Shelomo S KASSIN Pre1915": "Hoseni",
				"Knis Betesh Geniza List, Aleppo": "Hoseni",
				"ABRAHAM DWECK Pre1920": "Hoseni",
				"IDELSOHN Pre1923": "Hoseni",
				"S SAGIR Laniado": "Bayat",
				"M H Elias, SHIR HADASH, Jerusalem, 1930": "-",
				"ASHEAR list": "Hoseni",
				"ASHEAR NOTES 1936-1940": "Nahwand (preSukkot)",
				"ABRAHAM E SHREM ~1945": "Bayat",
				"Argentina 1947 & Ezra Mishanieh": "Hoseni",
				"Shire Zimra H S ABOUD Jerusalem, 1950": "Hoseni",
				"GABRIEL A SHREM 1964 SUHV": "Mehayar",
				"D KASSIN/ ISAAC CAIN; RODFE SEDEQ; MEXICO": "Bayat",
				"YOSEF YEHEZKEL Jerusalem 1975": "Shuri",
				"Ish Massliah \"Abia Renanot\" Tunisians": "Hoseni",
				"Shaare Zimra YANANI Buenos Aires, 01": "Bayat",
				"BOZO, Ades, Shir Ushbaha 2005": "Hoseni-Mehayar",
				"Yishaq Yeranen Halabi": "Hoseni",
				"MOSHE AMASH (Shami)": "Ajam",
				"EZRA MASLATON TARAB (Shami)": "Ajam",
				"ABRAHAM SHAMRICHA (Shami)": "Bayat",
				"Hallel VeZimrah, Greece List, 1926": "Nahawnd"
			}
			// Parsha.VZOS_HABERACHA is unused
		}

		data[Parsha.VAYAKHEL_PEKUDEI] = {
			...data[Parsha.VAYAKHEL],
		}
		data[Parsha.TAZRIA_METZORA] = {
			...data[Parsha.TAZRIA]
		},
		data[Parsha.ACHREI_MOS_KEDOSHIM] = {
			...data[Parsha.ACHREI_MOS]
		}
		data[Parsha.BEHAR_BECHUKOSAI] = {
			...data[Parsha.BEHAR]
		}
		data[Parsha.CHUKAS_BALAK] = {
			...data[Parsha.CHUKAS]
		}
		data[Parsha.MATOS_MASEI] = {
			...data[Parsha.MATOS]
		}
		data[Parsha.NITZAVIM_VAYEILECH] = {
			...data[Parsha.NITZAVIM]
		}

		if (jCal.getDayOfWeek() === Calendar.SATURDAY) {
			return data[jCal.getParshah()]!
		}

		if (jCal.getDayOfChanukah() !== -1) {
			return {
				1: {
					"SASSOON #647 Aleppo, 1850": "Rahawi",
					"GABRIEL A SHREM 1964 SUHV": "Rahawi",
					"ABRAHAM SHAMRICHA (Shami)": "Nawah"
				},
				2: {
					"SASSOON #647 Aleppo, 1850": "Iraq",
					"GABRIEL A SHREM 1964 SUHV": "Iraq"
				},
				3: {
					"SASSOON #647 Aleppo, 1850": "Sigah",
					"GABRIEL A SHREM 1964 SUHV": "Sigah"
				},
				4: {
					"SASSOON #647 Aleppo, 1850": "Saba",
					"GABRIEL A SHREM 1964 SUHV": "Saba"
				},
				5: {
					"SASSOON #647 Aleppo, 1850": "Rast",
					"GABRIEL A SHREM 1964 SUHV": "Rast"
				},
				6: {
					"GABRIEL A SHREM 1964 SUHV": "Nahwand"
				},
				7: {
					"GABRIEL A SHREM 1964 SUHV": "Sigah"
				},
				8: {
					"GABRIEL A SHREM 1964 SUHV": "Bayat"
				},
				[-1]: {}
			}[jCal.getDayOfChanukah()]
		}

		return {}
	}
}

function findDuplicate(arr:unknown[]) {
	arr.sort();
	let count = 1;
	let current = arr[1];
	let maxcount = 1;
	let maxelement = current;
  
	for (var i = 1; i < arr.length; i++) {
	  if (arr[i] === current) {
		count++;
	  } else {
		if (count > maxcount) {
		  maxcount = count;
		  maxelement = current;
		}
		current = arr[i];
		count = 1;
	  }
	}
	// in case the last element has the highest count
	if (count > maxcount) {
	  maxcount = count;
	  maxelement = current;
	}
  
	return maxelement;
  }